import { CrossTradeMapping, TradeCsiMappingRule } from "./types";

export const defaultTradeCsiMappings: TradeCsiMappingRule[] = [
  {
    id: "general-requirements-division-01",
    tradeId: "general-requirements",
    csiVersion: "ALL",
    codePatterns: ["01*", "00 7*", "007*"],
    titleKeywords: ["general requirements", "general conditions", "temporary facilities"],
    matchStrength: "SECONDARY",
  },
  {
    id: "earthwork-primary",
    tradeId: "earthwork",
    csiVersion: "ALL",
    codePatterns: ["31 0*", "31 1*", "31 2*", "310*", "311*", "312*", "02 2*", "022*"],
    titleKeywords: ["earthwork", "excavation", "grading", "clearing", "site preparation", "backfill"],
    matchStrength: "PRIMARY",
  },
  {
    id: "utilities-primary",
    tradeId: "utilities",
    csiVersion: "ALL",
    codePatterns: ["33*", "02 6*", "026*"],
    titleKeywords: ["utilities", "site utilities", "water utility", "sanitary sewer", "storm sewer", "utility"],
    matchStrength: "PRIMARY",
  },
  {
    id: "asphalt-paving-primary",
    tradeId: "asphalt-paving",
    csiVersion: "ALL",
    codePatterns: ["32 1*", "321*", "025*"],
    titleKeywords: ["asphalt", "paving", "pavement", "striping", "pavement marking"],
    matchStrength: "PRIMARY",
  },
  {
    id: "landscaping-primary",
    tradeId: "landscaping",
    csiVersion: "ALL",
    codePatterns: ["32 8*", "32 9*", "328*", "329*", "029*"],
    titleKeywords: ["landscape", "landscaping", "planting", "irrigation", "turf"],
    matchStrength: "PRIMARY",
  },
  {
    id: "concrete-primary",
    tradeId: "concrete",
    csiVersion: "ALL",
    codePatterns: ["03*"],
    titleKeywords: ["concrete", "cementitious", "formwork", "reinforcing", "precast"],
    matchStrength: "PRIMARY",
  },
  {
    id: "masonry-primary",
    tradeId: "masonry",
    csiVersion: "ALL",
    codePatterns: ["04*"],
    titleKeywords: ["masonry", "brick", "block", "cmu", "stone masonry"],
    matchStrength: "PRIMARY",
  },
  {
    id: "structural-steel-primary",
    tradeId: "structural-steel",
    csiVersion: "ALL",
    codePatterns: ["05 1*", "05 2*", "051*", "052*"],
    titleKeywords: ["structural steel", "steel joist", "metal deck", "steel framing"],
    matchStrength: "PRIMARY",
  },
  {
    id: "misc-metals-primary",
    tradeId: "misc-metals",
    csiVersion: "ALL",
    codePatterns: ["05 5*", "05 7*", "055*", "057*"],
    titleKeywords: ["miscellaneous metal", "metal fabrication", "railing", "ladder", "bollard"],
    matchStrength: "PRIMARY",
  },
  {
    id: "rough-carpentry-primary",
    tradeId: "rough-carpentry",
    csiVersion: "ALL",
    codePatterns: ["06 1*", "061*"],
    titleKeywords: ["rough carpentry", "blocking", "wood framing", "sheathing"],
    matchStrength: "PRIMARY",
  },
  {
    id: "finish-carpentry-millwork-primary",
    tradeId: "finish-carpentry-millwork",
    csiVersion: "ALL",
    codePatterns: ["06 2*", "06 4*", "062*", "064*"],
    titleKeywords: ["finish carpentry", "millwork", "architectural woodwork", "casework"],
    matchStrength: "PRIMARY",
  },
  {
    id: "roofing-primary",
    tradeId: "roofing",
    csiVersion: "ALL",
    codePatterns: ["07 3*", "073*"],
    titleKeywords: ["roofing", "roof", "shingle", "membrane roofing", "roof insulation"],
    matchStrength: "PRIMARY",
  },
  {
    id: "waterproofing-primary",
    tradeId: "waterproofing",
    csiVersion: "ALL",
    codePatterns: ["07 1*", "07 2*", "07 9*", "071*", "072*", "079*"],
    titleKeywords: ["waterproofing", "dampproofing", "air barrier", "sealant", "joint sealant"],
    matchStrength: "PRIMARY",
    notes: "Sealants may need review for overlap with glazing, roofing, or exterior walls.",
  },
  {
    id: "hollow-metal-doors-frames-primary",
    tradeId: "hollow-metal-doors-frames",
    csiVersion: "ALL",
    codePatterns: ["08 1*", "081*"],
    titleKeywords: ["hollow metal", "metal door", "metal frame"],
    matchStrength: "PRIMARY",
  },
  {
    id: "wood-doors-primary",
    tradeId: "wood-doors",
    csiVersion: "ALL",
    codePatterns: ["08 2*", "082*"],
    titleKeywords: ["wood door", "flush wood"],
    matchStrength: "PRIMARY",
  },
  {
    id: "door-hardware-primary",
    tradeId: "door-hardware",
    csiVersion: "ALL",
    codePatterns: ["08 7*", "087*"],
    titleKeywords: ["door hardware", "finish hardware", "hardware"],
    matchStrength: "PRIMARY",
  },
  {
    id: "access-doors-primary",
    tradeId: "access-doors",
    csiVersion: "ALL",
    codePatterns: ["08 3*", "083*"],
    titleKeywords: ["access door", "access panel"],
    matchStrength: "PRIMARY",
  },
  {
    id: "doors-frames-hardware-secondary",
    tradeId: "doors-frames-hardware",
    csiVersion: "ALL",
    codePatterns: ["08 1*", "08 2*", "08 3*", "08 7*", "081*", "082*", "083*", "087*"],
    titleKeywords: ["door", "frame", "hardware"],
    matchStrength: "SECONDARY",
  },
  {
    id: "storefront-primary",
    tradeId: "storefront",
    csiVersion: "ALL",
    codePatterns: ["08 4*", "084*"],
    titleKeywords: ["storefront", "entrance"],
    matchStrength: "PRIMARY",
  },
  {
    id: "curtain-wall-primary",
    tradeId: "curtain-wall",
    csiVersion: "ALL",
    codePatterns: ["08 4*", "084*"],
    titleKeywords: ["curtain wall", "curtainwall"],
    matchStrength: "PRIMARY",
  },
  {
    id: "interior-glass-primary",
    tradeId: "interior-glass-glazing",
    csiVersion: "ALL",
    codePatterns: ["08 8*", "088*"],
    titleKeywords: ["interior glass", "glass partition", "glazed partition"],
    matchStrength: "PRIMARY",
  },
  {
    id: "glass-glazing-secondary",
    tradeId: "glass-glazing",
    csiVersion: "ALL",
    codePatterns: ["08 4*", "08 8*", "084*", "088*"],
    titleKeywords: ["glass", "glazing", "storefront", "curtain wall", "window"],
    matchStrength: "SECONDARY",
  },
  {
    id: "non-structural-metal-framing-primary",
    tradeId: "non-structural-metal-framing",
    csiVersion: "ALL",
    codePatterns: ["09 22*", "0922*"],
    titleKeywords: ["metal stud", "metal framing", "non-structural metal framing"],
    matchStrength: "PRIMARY",
  },
  {
    id: "gypsum-board-primary",
    tradeId: "gypsum-board",
    csiVersion: "ALL",
    codePatterns: ["09 29*", "0929*"],
    titleKeywords: ["gypsum", "gypsum board", "drywall", "gwb"],
    matchStrength: "PRIMARY",
  },
  {
    id: "shaft-wall-primary",
    tradeId: "shaft-wall-assemblies",
    csiVersion: "ALL",
    codePatterns: ["09 21*", "09 29*", "0921*", "0929*"],
    titleKeywords: ["shaft wall", "shaftwall"],
    matchStrength: "PRIMARY",
  },
  {
    id: "plaster-primary",
    tradeId: "plaster",
    csiVersion: "ALL",
    codePatterns: ["09 23*", "09 24*", "0923*", "0924*"],
    titleKeywords: ["plaster", "veneer plaster"],
    matchStrength: "PRIMARY",
  },
  {
    id: "drywall-framing-secondary",
    tradeId: "drywall-framing",
    csiVersion: "ALL",
    codePatterns: ["09 2*", "092*"],
    titleKeywords: ["drywall", "gypsum", "metal stud", "metal framing", "shaft wall", "plaster"],
    matchStrength: "SECONDARY",
  },
  {
    id: "acoustical-ceilings-primary",
    tradeId: "acoustical-ceilings",
    csiVersion: "ALL",
    codePatterns: ["09 51*", "0951*"],
    titleKeywords: ["acoustical ceiling", "act", "ceiling tile"],
    matchStrength: "PRIMARY",
  },
  {
    id: "specialty-ceilings-primary",
    tradeId: "specialty-ceilings",
    csiVersion: "ALL",
    codePatterns: ["09 5*", "095*"],
    titleKeywords: ["specialty ceiling", "wood ceiling", "metal ceiling"],
    matchStrength: "PRIMARY",
  },
  {
    id: "carpet-primary",
    tradeId: "carpet",
    csiVersion: "ALL",
    codePatterns: ["09 68*", "0968*"],
    titleKeywords: ["carpet", "carpeting", "carpet tile"],
    matchStrength: "PRIMARY",
  },
  {
    id: "resilient-flooring-primary",
    tradeId: "resilient-flooring-lvt",
    csiVersion: "ALL",
    codePatterns: ["09 65*", "0965*"],
    titleKeywords: ["resilient", "lvt", "vinyl flooring", "vct", "rubber flooring"],
    matchStrength: "PRIMARY",
  },
  {
    id: "tile-primary",
    tradeId: "tile",
    csiVersion: "ALL",
    codePatterns: ["09 30*", "093*"],
    titleKeywords: ["tile", "tiling", "ceramic tile", "porcelain tile", "stone tile"],
    matchStrength: "PRIMARY",
  },
  {
    id: "wood-flooring-primary",
    tradeId: "wood-flooring",
    csiVersion: "ALL",
    codePatterns: ["09 64*", "0964*"],
    titleKeywords: ["wood flooring", "hardwood flooring"],
    matchStrength: "PRIMARY",
  },
  {
    id: "resinous-epoxy-flooring-primary",
    tradeId: "resinous-epoxy-flooring",
    csiVersion: "ALL",
    codePatterns: ["09 67*", "0967*"],
    titleKeywords: ["resinous", "epoxy flooring", "fluid-applied flooring"],
    matchStrength: "PRIMARY",
  },
  {
    id: "flooring-prep-primary",
    tradeId: "flooring-prep-moisture-mitigation",
    csiVersion: "ALL",
    codePatterns: ["09 05*", "0905*"],
    titleKeywords: ["floor prep", "moisture mitigation", "self-leveling", "underlayment"],
    matchStrength: "PRIMARY",
  },
  {
    id: "flooring-secondary",
    tradeId: "flooring",
    csiVersion: "ALL",
    codePatterns: ["09 3*", "09 6*", "093*", "096*"],
    titleKeywords: ["flooring", "floor finish"],
    matchStrength: "SECONDARY",
  },
  {
    id: "painting-coatings-primary",
    tradeId: "painting-coatings",
    csiVersion: "ALL",
    codePatterns: ["09 9*", "099*"],
    titleKeywords: ["painting", "paint", "coating", "wall covering", "wallcovering"],
    matchStrength: "PRIMARY",
  },
  {
    id: "specialties-primary",
    tradeId: "specialties",
    csiVersion: "ALL",
    codePatterns: ["10*"],
    titleKeywords: ["specialties", "signage", "toilet accessory", "locker", "partition"],
    matchStrength: "PRIMARY",
  },
  {
    id: "equipment-primary",
    tradeId: "equipment",
    csiVersion: "ALL",
    codePatterns: ["11*"],
    titleKeywords: ["equipment"],
    matchStrength: "PRIMARY",
  },
  {
    id: "fire-protection-primary",
    tradeId: "fire-protection",
    csiVersion: "ALL",
    codePatterns: ["21*", "153*"],
    titleKeywords: ["fire protection", "fire suppression", "sprinkler"],
    matchStrength: "PRIMARY",
  },
  {
    id: "plumbing-primary",
    tradeId: "plumbing",
    csiVersion: "ALL",
    codePatterns: ["22*", "154*"],
    titleKeywords: ["plumbing", "domestic water", "sanitary", "plumbing fixture", "plumbing piping"],
    matchStrength: "PRIMARY",
  },
  {
    id: "hvac-equipment-primary",
    tradeId: "hvac-equipment",
    csiVersion: "ALL",
    codePatterns: ["23 7*", "237*", "157*"],
    titleKeywords: ["hvac equipment", "air handling", "rooftop unit", "mechanical equipment"],
    matchStrength: "PRIMARY",
  },
  {
    id: "ductwork-air-distribution-primary",
    tradeId: "ductwork-air-distribution",
    csiVersion: "ALL",
    codePatterns: ["23 3*", "233*", "158*"],
    titleKeywords: ["duct", "ductwork", "air distribution", "diffuser", "grille"],
    matchStrength: "PRIMARY",
  },
  {
    id: "controls-primary",
    tradeId: "controls",
    csiVersion: "ALL",
    codePatterns: ["23 09*", "2309*", "159*"],
    titleKeywords: ["controls", "temperature controls", "building automation", "bas"],
    matchStrength: "PRIMARY",
  },
  {
    id: "hvac-secondary",
    tradeId: "hvac",
    csiVersion: "ALL",
    codePatterns: ["23*", "155*", "156*", "157*", "158*", "159*"],
    titleKeywords: ["hvac", "mechanical", "heating", "ventilating", "air conditioning"],
    matchStrength: "SECONDARY",
  },
  {
    id: "power-distribution-primary",
    tradeId: "power-distribution",
    csiVersion: "ALL",
    codePatterns: ["26 2*", "26 3*", "262*", "263*", "164*"],
    titleKeywords: ["power distribution", "switchgear", "panelboard", "transformer"],
    matchStrength: "PRIMARY",
  },
  {
    id: "lighting-primary",
    tradeId: "lighting",
    csiVersion: "ALL",
    codePatterns: ["26 5*", "265*", "165*"],
    titleKeywords: ["lighting", "light fixture", "luminaire"],
    matchStrength: "PRIMARY",
  },
  {
    id: "devices-primary",
    tradeId: "devices",
    csiVersion: "ALL",
    codePatterns: ["26 27*", "2627*"],
    titleKeywords: ["devices", "wiring devices", "receptacle", "switch"],
    matchStrength: "PRIMARY",
  },
  {
    id: "electrical-secondary",
    tradeId: "electrical",
    csiVersion: "ALL",
    codePatterns: ["26*", "16*"],
    titleKeywords: ["electrical", "power", "lighting", "panels", "devices"],
    matchStrength: "SECONDARY",
  },
  {
    id: "data-communications-primary",
    tradeId: "data-communications",
    csiVersion: "ALL",
    codePatterns: ["27*", "167*"],
    titleKeywords: ["data", "communications", "telecommunications", "network"],
    matchStrength: "PRIMARY",
  },
  {
    id: "security-access-control-primary",
    tradeId: "security-access-control",
    csiVersion: "ALL",
    codePatterns: ["28 1*", "281*"],
    titleKeywords: ["security", "access control", "cctv", "surveillance"],
    matchStrength: "PRIMARY",
  },
  {
    id: "av-primary",
    tradeId: "av",
    csiVersion: "ALL",
    codePatterns: ["27 4*", "274*"],
    titleKeywords: ["audio visual", "audiovisual", "av"],
    matchStrength: "PRIMARY",
  },
  {
    id: "fire-alarm-primary",
    tradeId: "fire-alarm",
    csiVersion: "ALL",
    codePatterns: ["28 3*", "283*"],
    titleKeywords: ["fire alarm", "detection and alarm"],
    matchStrength: "PRIMARY",
  },
  {
    id: "low-voltage-secondary",
    tradeId: "low-voltage-technology",
    csiVersion: "ALL",
    codePatterns: ["27*", "28*"],
    titleKeywords: ["low voltage", "technology", "communications", "security", "access control", "av"],
    matchStrength: "SECONDARY",
  },
];

export const defaultCrossTradeMappings: CrossTradeMapping[] = [
  {
    id: "fire-alarm-cross-trade",
    label: "Fire Alarm",
    primaryTradeId: "fire-alarm",
    possibleTradeIds: ["electrical", "low-voltage-technology", "fire-protection"],
    sectorPreferredTradeIds: {
      healthcare: "low-voltage-technology",
      mission_critical: "low-voltage-technology",
      industrial: "electrical",
    },
    contextPreferredTradeIds: {
      medical_office: "low-voltage-technology",
      hospital: "low-voltage-technology",
      surgery_center: "low-voltage-technology",
      secure_facility: "low-voltage-technology",
    },
    csiCodePatterns: ["28 3*", "283*"],
    titleKeywords: ["fire alarm", "detection and alarm"],
    notes: "Fire alarm may be carried by electrical, low-voltage, or fire protection depending on project delivery.",
  },
  {
    id: "controls-bas-cross-trade",
    label: "Controls / BAS",
    primaryTradeId: "controls",
    possibleTradeIds: ["hvac", "electrical", "low-voltage-technology"],
    sectorPreferredTradeIds: {
      laboratory: "hvac",
      cleanroom: "hvac",
      mission_critical: "low-voltage-technology",
    },
    contextPreferredTradeIds: {
      lab: "hvac",
      cleanroom: "hvac",
      data_center: "low-voltage-technology",
    },
    csiCodePatterns: ["23 09*", "2309*", "25*", "159*"],
    titleKeywords: ["controls", "building automation", "bas", "temperature controls"],
    notes: "Controls may be packaged with HVAC, electrical, or low-voltage systems.",
  },
  {
    id: "countertops-cross-trade",
    label: "Countertops",
    primaryTradeId: "countertops",
    possibleTradeIds: ["finish-carpentry-millwork", "tile", "specialties"],
    sectorPreferredTradeIds: {
      restaurant: "countertops",
      hospitality: "countertops",
      healthcare: "countertops",
    },
    csiCodePatterns: ["06 4*", "064*", "12 36*", "1236*"],
    titleKeywords: ["countertop", "countertops", "solid surface", "quartz", "granite", "stone countertop"],
    notes: "Laminate tops may travel with millwork; stone, quartz, or granite may be separate.",
  },
  {
    id: "acoustic-insulation-cross-trade",
    label: "Acoustic Insulation",
    primaryTradeId: "drywall-framing",
    possibleTradeIds: ["insulation", "ceilings"],
    sectorPreferredTradeIds: {
      education: "ceilings",
      office: "drywall-framing",
    },
    csiCodePatterns: ["09 2*", "092*", "07 21*", "0721*"],
    titleKeywords: ["acoustic insulation", "acoustical insulation", "sound batt", "sound insulation"],
    notes: "Acoustic insulation can be carried with drywall, insulation, or ceiling scopes.",
  },
  {
    id: "kitchen-hood-cross-trade",
    label: "Kitchen Hood",
    primaryTradeId: "kitchen-exhaust",
    possibleTradeIds: ["hvac", "food-service-systems", "fire-protection"],
    sectorPreferredTradeIds: {
      restaurant: "food-service-systems",
      hospitality: "food-service-systems",
    },
    contextPreferredTradeIds: {
      commercial_kitchen: "food-service-systems",
      food_processing: "food-service-systems",
    },
    csiCodePatterns: ["11 40*", "1140*", "23 38*", "2338*", "21 22*", "2122*"],
    titleKeywords: ["kitchen hood", "hood suppression", "commercial kitchen hood", "kitchen exhaust"],
    notes: "Kitchen hood scope may involve HVAC, food service equipment, and fire suppression.",
  },
  {
    id: "medical-gas-cross-trade",
    label: "Medical Gas",
    primaryTradeId: "medical-gas",
    possibleTradeIds: ["plumbing", "healthcare-systems"],
    sectorPreferredTradeIds: {
      healthcare: "healthcare-systems",
      laboratory: "medical-gas",
    },
    contextPreferredTradeIds: {
      medical_office: "medical-gas",
      hospital: "medical-gas",
      surgery_center: "medical-gas",
      lab: "medical-gas",
    },
    csiCodePatterns: ["22 60*", "2260*"],
    titleKeywords: ["medical gas", "med gas", "medical gas piping"],
    notes: "Medical gas may be managed as plumbing scope or a healthcare specialty package.",
  },
  {
    id: "polished-concrete-cross-trade",
    label: "Polished Concrete",
    primaryTradeId: "polished-concrete",
    possibleTradeIds: ["concrete", "flooring"],
    sectorPreferredTradeIds: {
      retail: "flooring",
      office: "flooring",
    },
    csiCodePatterns: ["03 35*", "0335*", "09 62*", "0962*"],
    titleKeywords: ["polished concrete", "concrete polishing"],
    notes: "Polished concrete can sit with concrete finishing or flooring.",
  },
  {
    id: "loading-dock-equipment-cross-trade",
    label: "Loading Dock Equipment",
    primaryTradeId: "loading-dock-equipment",
    possibleTradeIds: ["overhead-doors", "equipment"],
    sectorPreferredTradeIds: {
      warehouse: "overhead-doors",
      industrial: "overhead-doors",
    },
    csiCodePatterns: ["11 13*", "1113*", "08 33*", "0833*"],
    titleKeywords: ["loading dock", "dock leveler", "dock seal", "dock shelter"],
    notes: "Loading dock equipment may be packaged with overhead doors or equipment.",
  },
  {
    id: "nurse-call-cross-trade",
    label: "Nurse Call",
    primaryTradeId: "nurse-call",
    possibleTradeIds: ["low-voltage-technology", "healthcare-systems"],
    sectorPreferredTradeIds: {
      healthcare: "healthcare-systems",
    },
    contextPreferredTradeIds: {
      medical_office: "nurse-call",
      hospital: "nurse-call",
      surgery_center: "nurse-call",
    },
    csiCodePatterns: ["27 52*", "2752*"],
    titleKeywords: ["nurse call"],
    notes: "Nurse call is low-voltage but usually healthcare-sector specific.",
  },
  {
    id: "pneumatic-tubes-cross-trade",
    label: "Pneumatic Tubes",
    primaryTradeId: "pneumatic-tube-systems",
    possibleTradeIds: ["conveying", "healthcare-systems"],
    sectorPreferredTradeIds: {
      healthcare: "healthcare-systems",
      laboratory: "healthcare-systems",
    },
    contextPreferredTradeIds: {
      hospital: "pneumatic-tube-systems",
      lab: "pneumatic-tube-systems",
    },
    csiCodePatterns: ["14 92*", "1492*"],
    titleKeywords: ["pneumatic tube", "pneumatic tubes"],
    notes: "Pneumatic tube systems can be managed as conveying or healthcare specialty scope.",
  },
  {
    id: "lab-gases-cross-trade",
    label: "Lab Gases",
    primaryTradeId: "plumbing-process-piping",
    possibleTradeIds: ["plumbing", "laboratory-cleanroom-systems"],
    sectorPreferredTradeIds: {
      laboratory: "laboratory-cleanroom-systems",
      cleanroom: "laboratory-cleanroom-systems",
    },
    contextPreferredTradeIds: {
      lab: "laboratory-cleanroom-systems",
      cleanroom: "laboratory-cleanroom-systems",
    },
    csiCodePatterns: ["22 60*", "2260*", "22 67*", "2267*"],
    titleKeywords: ["lab gas", "laboratory gas", "specialty gas", "process gas"],
    notes: "Lab gases can be plumbing/process piping or laboratory specialty scope.",
  },
  {
    id: "cleanroom-systems-cross-trade",
    label: "Cleanroom Systems",
    primaryTradeId: "laboratory-cleanroom-systems",
    possibleTradeIds: ["hvac", "painting-coatings", "frp-panels"],
    sectorPreferredTradeIds: {
      cleanroom: "laboratory-cleanroom-systems",
      laboratory: "laboratory-cleanroom-systems",
    },
    contextPreferredTradeIds: {
      cleanroom: "laboratory-cleanroom-systems",
      lab: "laboratory-cleanroom-systems",
    },
    csiCodePatterns: ["13 21*", "1321*"],
    titleKeywords: ["cleanroom", "clean room", "cleanroom panel", "cleanroom system"],
    notes: "Cleanroom systems may involve lab specialty scope, HVAC, and interior panel systems.",
  },
];
