import { TradeTaxonomyNode } from "./types";

export const defaultTradeTaxonomy: TradeTaxonomyNode[] = [
  {
    id: "general-requirements",
    name: "General Requirements",
    aliases: ["General Conditions", "Division 01"],
    description: "Project-wide requirements, temporary facilities, supervision, and administrative scope.",
    sortOrder: 10,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    defaultScopeNotes: ["Use when project-wide requirements are bid separately."],
    isActive: true,
  },
  {
    id: "sitework",
    name: "Sitework",
    aliases: ["Civil", "Site"],
    description: "Exterior site, civil, earthwork, utilities, paving, and landscape scope.",
    sortOrder: 20,
    canBeBidPackage: true,
    defaultPackageMode: "SPLIT_BY_CHILD",
    defaultScopeNotes: ["Split sitework by child trade when the project has meaningful civil scope separation."],
    isActive: true,
  },
  {
    id: "earthwork",
    parentId: "sitework",
    name: "Earthwork",
    aliases: ["Excavation", "Grading", "Site Prep"],
    sortOrder: 22,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "demolition",
    parentId: "sitework",
    name: "Demolition",
    aliases: ["Demo", "Selective Demolition", "Site Demolition"],
    sortOrder: 21,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "utilities",
    parentId: "sitework",
    name: "Utilities",
    aliases: ["Site Utilities", "Wet Utilities", "Dry Utilities"],
    sortOrder: 23,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "asphalt-paving",
    parentId: "sitework",
    name: "Asphalt / Paving",
    aliases: ["Paving", "Pavement", "Striping"],
    sortOrder: 24,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "landscaping",
    parentId: "sitework",
    name: "Landscaping",
    aliases: ["Landscape", "Planting", "Irrigation"],
    sortOrder: 25,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "concrete",
    name: "Concrete",
    aliases: ["Cast-in-Place Concrete", "Precast Concrete"],
    sortOrder: 30,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "cast-in-place-concrete",
    parentId: "concrete",
    name: "Cast-In-Place Concrete",
    aliases: ["CIP Concrete", "Cast in Place", "Concrete Slabs", "Foundations"],
    sortOrder: 31,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "tilt-up-concrete",
    parentId: "concrete",
    name: "Tilt-Up Concrete",
    aliases: ["Tilt Wall", "Tilt-Up Panels"],
    sortOrder: 32,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "precast-concrete",
    parentId: "concrete",
    name: "Precast Concrete",
    aliases: ["Precast", "Precast Panels", "Architectural Precast"],
    sortOrder: 33,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "shotcrete",
    parentId: "concrete",
    name: "Shotcrete",
    aliases: ["Gunite"],
    sortOrder: 34,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "masonry",
    name: "Masonry",
    aliases: ["CMU", "Brick", "Stone Masonry"],
    sortOrder: 40,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "cmu-brick-masonry",
    parentId: "masonry",
    name: "CMU / Brick Masonry",
    aliases: ["CMU", "Brick", "Block Masonry"],
    sortOrder: 41,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "stone-masonry",
    parentId: "masonry",
    name: "Stone Masonry",
    aliases: ["Natural Stone", "Stone Veneer"],
    sortOrder: 42,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "simulated-masonry",
    parentId: "masonry",
    name: "Simulated Masonry",
    aliases: ["Manufactured Stone", "Cast Stone Veneer", "Faux Stone"],
    sortOrder: 43,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "structural-steel",
    name: "Structural Steel",
    aliases: ["Steel", "Steel Framing", "Joists", "Metal Deck"],
    sortOrder: 50,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "misc-metals",
    name: "Misc Metals",
    aliases: ["Miscellaneous Metals", "Railings", "Metal Fabrications"],
    sortOrder: 60,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "architectural-metals",
    parentId: "misc-metals",
    name: "Architectural Metals",
    aliases: ["Architectural Metalwork", "Decorative Metals", "Metal Fabrications"],
    sortOrder: 61,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "railings",
    parentId: "misc-metals",
    name: "Railings",
    aliases: ["Guardrails", "Handrails", "Stair Railings"],
    sortOrder: 62,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "rough-carpentry",
    name: "Rough Carpentry",
    aliases: ["Blocking", "Wood Framing", "Sheathing"],
    sortOrder: 70,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "finish-carpentry-millwork",
    name: "Finish Carpentry / Millwork",
    aliases: ["Millwork", "Architectural Woodwork", "Casework"],
    sortOrder: 80,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "countertops",
    parentId: "finish-carpentry-millwork",
    name: "Countertops",
    aliases: [
      "Plastic Laminate Countertops",
      "Solid Surface Countertops",
      "Stone Countertops",
      "Quartz Countertops",
      "Granite Countertops",
    ],
    description:
      "Countertop scope that may travel with millwork or split into a separate stone, quartz, granite, or solid-surface package.",
    sortOrder: 81,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    defaultScopeNotes: [
      "Plastic laminate tops may be included with millwork.",
      "Stone, quartz, granite, or solid-surface tops may need a separate bid package.",
    ],
    isActive: true,
  },
  {
    id: "roofing",
    name: "Roofing",
    aliases: ["Roof", "Membrane Roofing", "Shingles"],
    sortOrder: 90,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "membrane-roofing",
    parentId: "roofing",
    name: "Membrane Roofing",
    aliases: ["TPO", "EPDM", "PVC Roofing", "Single-Ply Roofing"],
    sortOrder: 91,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "sheet-metal-roofing",
    parentId: "roofing",
    name: "Sheet Metal Roofing",
    aliases: ["Metal Roofing", "Roof Sheet Metal", "Flashing"],
    sortOrder: 92,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "shingle-roofing",
    parentId: "roofing",
    name: "Shingle Roofing",
    aliases: ["Asphalt Shingles", "Roof Shingles"],
    sortOrder: 93,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "waterproofing",
    name: "Waterproofing",
    aliases: ["Dampproofing", "Air Barrier", "Sealants"],
    sortOrder: 100,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    defaultScopeNotes: ["Review sealants and air barrier scope for overlap with glazing, roofing, or exterior wall packages."],
    isActive: true,
  },
  {
    id: "doors-frames-hardware",
    name: "Doors / Frames / Hardware",
    aliases: ["DFH", "Doors and Hardware"],
    description: "Doors, frames, hardware, and closely related access opening scope.",
    sortOrder: 110,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    defaultScopeNotes: ["Usually bid as a single coordinated package."],
    isActive: true,
  },
  {
    id: "hollow-metal-doors-frames",
    parentId: "doors-frames-hardware",
    name: "Hollow Metal Doors / Frames",
    aliases: ["Hollow Metal", "HM Doors", "HM Frames"],
    sortOrder: 111,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "wood-doors",
    parentId: "doors-frames-hardware",
    name: "Wood Doors",
    aliases: ["Flush Wood Doors"],
    sortOrder: 112,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "door-hardware",
    parentId: "doors-frames-hardware",
    name: "Door Hardware",
    aliases: ["Hardware", "Finish Hardware"],
    sortOrder: 113,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "access-doors",
    parentId: "doors-frames-hardware",
    name: "Access Doors",
    aliases: ["Access Panels"],
    sortOrder: 114,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "overhead-doors",
    name: "Overhead Doors",
    aliases: ["Sectional Doors", "Coiling Doors", "Rolling Doors", "Loading Dock Doors"],
    description:
      "Overhead, sectional, coiling, rolling, and loading dock door scope that is often bid separately from DFH.",
    sortOrder: 115,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "glass-glazing",
    name: "Glass / Glazing",
    aliases: ["Glazing", "Storefront", "Curtain Wall"],
    sortOrder: 120,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "storefront",
    parentId: "glass-glazing",
    name: "Storefront",
    aliases: ["Aluminum Storefront"],
    sortOrder: 121,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "curtain-wall",
    parentId: "glass-glazing",
    name: "Curtain Wall",
    aliases: ["Curtainwall"],
    sortOrder: 122,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "interior-glass-glazing",
    parentId: "glass-glazing",
    name: "Interior Glass / Glazing",
    aliases: ["Interior Glass", "Glass Partitions"],
    sortOrder: 123,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "drywall-framing",
    name: "Drywall / Framing",
    aliases: ["Drywall", "Gypsum Board", "Metal Stud Framing"],
    description: "Interior framing, gypsum board, shaft wall, plaster, and related drywall assemblies.",
    sortOrder: 130,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    defaultScopeNotes: ["Gypsum board and metal stud framing should typically roll into one package."],
    defaultExclusions: ["ACT ceilings unless intentionally included.", "Painting unless intentionally included."],
    isActive: true,
  },
  {
    id: "non-structural-metal-framing",
    parentId: "drywall-framing",
    name: "Non-Structural Metal Framing",
    aliases: ["Metal Studs", "Metal Framing"],
    sortOrder: 131,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "gypsum-board",
    parentId: "drywall-framing",
    name: "Gypsum Board",
    aliases: ["Drywall", "GWB"],
    sortOrder: 132,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "shaft-wall-assemblies",
    parentId: "drywall-framing",
    name: "Shaft Wall Assemblies",
    aliases: ["Shaft Wall", "Shaftwall"],
    sortOrder: 133,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "plaster",
    parentId: "drywall-framing",
    name: "Plaster",
    aliases: ["Gypsum Plaster", "Veneer Plaster"],
    sortOrder: 134,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "ceilings",
    name: "Ceilings",
    aliases: ["ACT", "Acoustical Ceilings"],
    sortOrder: 140,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "acoustical-ceilings",
    parentId: "ceilings",
    name: "Acoustical Ceilings",
    aliases: ["ACT", "Acoustical Ceiling Tile"],
    sortOrder: 141,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "specialty-ceilings",
    parentId: "ceilings",
    name: "Specialty Ceilings",
    aliases: ["Wood Ceilings", "Metal Ceilings"],
    sortOrder: 142,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "flooring",
    name: "Flooring",
    aliases: ["Floor Finishes"],
    description: "Floor finishes and substrate preparation scope.",
    sortOrder: 150,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    defaultScopeNotes: ["Choose umbrella or split child packages based on project size and subcontractor market."],
    isActive: true,
  },
  {
    id: "carpet",
    parentId: "flooring",
    name: "Carpet",
    aliases: ["Carpet Tile", "Broadloom"],
    sortOrder: 151,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "resilient-flooring-lvt",
    parentId: "flooring",
    name: "Resilient Flooring / LVT",
    aliases: ["LVT", "VCT", "Resilient"],
    sortOrder: 152,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "tile",
    parentId: "flooring",
    name: "Tile",
    aliases: ["Ceramic Tile", "Porcelain Tile", "Stone Tile"],
    sortOrder: 153,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "wood-flooring",
    parentId: "flooring",
    name: "Wood Flooring",
    aliases: ["Hardwood Flooring"],
    sortOrder: 154,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "resinous-epoxy-flooring",
    parentId: "flooring",
    name: "Resinous / Epoxy Flooring",
    aliases: ["Epoxy Flooring", "Resinous Flooring"],
    sortOrder: 155,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "flooring-prep-moisture-mitigation",
    parentId: "flooring",
    name: "Flooring Prep / Moisture Mitigation",
    aliases: ["Floor Prep", "Moisture Mitigation", "Self-Leveling"],
    sortOrder: 156,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "painting-coatings",
    name: "Painting / Coatings",
    aliases: ["Painting", "Coatings", "Wall Finishes"],
    sortOrder: 160,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  // TODO: Specialties needs a separate estimator review before adding toilet accessories,
  // fire extinguishers, lockers, signage, and similar specialty breakdowns.
  {
    id: "specialties",
    name: "Specialties",
    aliases: ["Division 10", "Accessories", "Signage"],
    sortOrder: 170,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "equipment",
    name: "Equipment",
    aliases: ["Division 11"],
    sortOrder: 180,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "fire-protection",
    name: "Fire Protection",
    aliases: ["Sprinklers", "Fire Suppression"],
    sortOrder: 190,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "plumbing",
    name: "Plumbing",
    aliases: ["Plumbing Fixtures", "Plumbing Piping"],
    sortOrder: 200,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "medical-gas",
    parentId: "plumbing",
    name: "Medical Gas",
    aliases: ["Med Gas", "Medical Gas Piping"],
    sortOrder: 201,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "hvac",
    name: "HVAC",
    aliases: ["Mechanical", "Heating Ventilating Air Conditioning"],
    sortOrder: 210,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "hvac-equipment",
    parentId: "hvac",
    name: "HVAC Equipment",
    aliases: ["Mechanical Equipment"],
    sortOrder: 211,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "ductwork-air-distribution",
    parentId: "hvac",
    name: "Ductwork / Air Distribution",
    aliases: ["Ductwork", "Air Distribution"],
    sortOrder: 212,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "controls",
    parentId: "hvac",
    name: "Controls",
    aliases: ["Building Automation", "BAS", "Temperature Controls"],
    sortOrder: 213,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "electrical",
    name: "Electrical",
    aliases: ["Power", "Lighting"],
    sortOrder: 220,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "power-distribution",
    parentId: "electrical",
    name: "Power Distribution",
    aliases: ["Distribution", "Switchgear", "Panels"],
    sortOrder: 221,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "lighting",
    parentId: "electrical",
    name: "Lighting",
    aliases: ["Light Fixtures", "Lighting Controls"],
    sortOrder: 222,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
  {
    id: "devices",
    parentId: "electrical",
    name: "Devices",
    aliases: ["Wiring Devices", "Receptacles", "Switches"],
    sortOrder: 223,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "low-voltage-technology",
    name: "Low Voltage / Technology",
    aliases: ["Low Voltage", "Technology", "Communications"],
    sortOrder: 230,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    defaultScopeNotes: ["Split by child system when specialist subcontractors are expected."],
    isActive: true,
  },
  {
    id: "data-communications",
    parentId: "low-voltage-technology",
    name: "Data / Communications",
    aliases: ["Data", "Telecom", "Communications"],
    sortOrder: 231,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "security-access-control",
    parentId: "low-voltage-technology",
    name: "Security / Access Control",
    aliases: ["Security", "Access Control", "CCTV"],
    sortOrder: 232,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "av",
    parentId: "low-voltage-technology",
    name: "AV",
    aliases: ["Audio Visual", "Audiovisual"],
    sortOrder: 233,
    canBeBidPackage: true,
    defaultPackageMode: "UMBRELLA",
    isActive: true,
  },
  {
    id: "fire-alarm",
    parentId: "low-voltage-technology",
    name: "Fire Alarm",
    aliases: ["FA"],
    sortOrder: 234,
    canBeBidPackage: true,
    defaultPackageMode: "USER_CHOICE",
    isActive: true,
  },
];

export function getDefaultTradeTaxonomy(): TradeTaxonomyNode[] {
  return defaultTradeTaxonomy.map((node) => ({ ...node }));
}

export function getTradeById(id: string): TradeTaxonomyNode | undefined {
  const trade = defaultTradeTaxonomy.find((node) => node.id === id);

  return trade ? { ...trade } : undefined;
}

export function getTradeChildren(parentId: string): TradeTaxonomyNode[] {
  return defaultTradeTaxonomy
    .filter((node) => node.parentId === parentId)
    .sort(compareTradeNodes)
    .map((node) => ({ ...node }));
}

export function getTradeAncestors(id: string): TradeTaxonomyNode[] {
  const ancestors: TradeTaxonomyNode[] = [];
  let currentNode = defaultTradeTaxonomy.find((node) => node.id === id);

  while (currentNode?.parentId) {
    const parentNode = defaultTradeTaxonomy.find(
      (node) => node.id === currentNode?.parentId
    );

    if (!parentNode) break;
    ancestors.unshift({ ...parentNode });
    currentNode = parentNode;
  }

  return ancestors;
}

function compareTradeNodes(
  leftNode: TradeTaxonomyNode,
  rightNode: TradeTaxonomyNode
) {
  return leftNode.sortOrder - rightNode.sortOrder;
}
