import {
  ContextTagAvailability,
  FacilityTypeAvailability,
  ProjectContractType,
  ProjectOwnerVendorScope,
  ProjectProfileBuildingCondition,
  ProjectProfileContextTagId,
  ProjectProfileFacilityTypeId,
  ProjectProfileOccupancyCondition,
  ProjectProfileOption,
  ProjectProfileScopeFlag,
  ProjectProfileSectorId,
  ProjectProfileStructureType,
  ProjectProfileWorkTypeId,
  ProjectPublicPrivateStatus,
  ProjectSiteWalkStatus,
  ProjectTaxStatus,
  SectorWorkTypeLabel,
} from "./types";

export const projectProfileSectorOptions: ProjectProfileOption<ProjectProfileSectorId>[] = [
  { id: "commercial", label: "Commercial", description: "General commercial project where no narrower sector has been selected.", sortOrder: 10 },
  { id: "office", label: "Office", description: "Office buildings, tenant suites, corporate interiors, and office fit-outs.", sortOrder: 20 },
  { id: "retail", label: "Retail", description: "Retail stores, shopping centers, storefronts, and sales environments.", sortOrder: 30 },
  { id: "restaurant", label: "Restaurant", description: "Restaurants, cafes, bars, commercial kitchens, and food service tenant spaces.", sortOrder: 40 },
  { id: "hospitality", label: "Hospitality", description: "Hotels, resorts, guestrooms, lobbies, amenity spaces, and hospitality back-of-house work.", sortOrder: 50 },
  { id: "healthcare", label: "Healthcare", description: "Medical office, clinic, hospital, surgery center, imaging, and healthcare support spaces.", sortOrder: 60 },
  { id: "education", label: "Education", description: "Schools, colleges, universities, classrooms, labs, cafeterias, and campus facilities.", sortOrder: 70 },
  { id: "industrial", label: "Industrial", description: "Industrial, manufacturing, process, utility, and production facilities.", sortOrder: 80 },
  { id: "warehouse", label: "Warehouse", description: "Warehouse, logistics, distribution, storage, fulfillment, and light industrial shell/buildout work.", sortOrder: 90 },
  { id: "laboratory", label: "Laboratory", description: "Laboratory, research, testing, and technical/scientific facilities.", sortOrder: 100 },
  { id: "cleanroom", label: "Cleanroom", description: "Cleanroom, controlled environment, and specialty technical production spaces.", sortOrder: 110 },
  { id: "multifamily", label: "Multifamily", description: "Apartment buildings, mixed-use residential, multifamily common areas, and unit renovations.", sortOrder: 120 },
  { id: "residential", label: "Residential", description: "Single-family residential, townhomes, custom homes, and residential remodels.", sortOrder: 130 },
  { id: "civil_sitework", label: "Civil / Sitework", description: "Site/civil, utilities, paving, earthwork, landscaping, and exterior development projects.", sortOrder: 140 },
  { id: "government", label: "Government", description: "Public agency, municipal, state, federal, and civic projects.", sortOrder: 150 },
  { id: "detention", label: "Detention", description: "Correctional, detention, holding, and secure custodial facilities.", sortOrder: 160 },
  { id: "transportation", label: "Transportation", description: "Transit, station, roadway, rail, airport, marine, and transportation infrastructure facilities.", sortOrder: 170 },
  { id: "airport", label: "Airport", description: "Airport, airfield, terminal, hangar, and secure aviation environments.", sortOrder: 180 },
  { id: "marine", label: "Marine / Waterfront", description: "Marine, dock, waterfront, pier, seawall, and shoreline work.", sortOrder: 190 },
  { id: "sports", label: "Sports / Recreation", description: "Athletic, recreation, sports fields, pools, performance, and event facilities.", sortOrder: 200 },
  { id: "mission_critical", label: "Mission Critical", description: "Data centers, critical facilities, UPS/generator-heavy environments, and resilient infrastructure.", sortOrder: 210 },
  { id: "renewable_energy", label: "Renewable Energy", description: "Solar, wind, EV charging, battery, and renewable infrastructure projects.", sortOrder: 220 },
  { id: "agricultural", label: "Agricultural", description: "Agricultural, greenhouse, grow, livestock, food production, and related facilities.", sortOrder: 230 },
];

export const projectProfileFacilityTypeOptions: ProjectProfileOption<ProjectProfileFacilityTypeId>[] = [
  { id: "general_office", label: "General Office", description: "General office space without a more specific facility subtype.", sortOrder: 10 },
  { id: "corporate_office", label: "Corporate Office", description: "Corporate headquarters, administrative offices, and corporate workplace environments.", sortOrder: 20 },
  { id: "professional_office", label: "Professional Office", description: "Professional service offices such as legal, accounting, consulting, or similar tenant spaces.", sortOrder: 30 },
  { id: "bank_branch", label: "Bank Branch", description: "Retail banking, credit union, teller, vault, or financial service branch spaces.", sortOrder: 40 },
  { id: "call_center", label: "Call Center", description: "Call center, contact center, support center, or high-density workstation environment.", sortOrder: 50 },
  { id: "coworking", label: "Coworking", description: "Coworking, shared office, flexible suite, or serviced workplace environment.", sortOrder: 60 },
  { id: "medical_office_facility", label: "Medical Office", description: "Medical office building, outpatient medical suite, or similar healthcare office facility.", sortOrder: 110 },
  { id: "clinic", label: "Clinic", description: "Clinic, outpatient clinic, urgent care, or ambulatory care facility.", sortOrder: 120 },
  { id: "surgery_center_facility", label: "Surgery Center", description: "Surgery center or ambulatory surgical facility.", sortOrder: 130 },
  { id: "imaging_center", label: "Imaging Center", description: "Imaging, radiology, MRI, CT, X-ray, or diagnostic imaging facility.", sortOrder: 140 },
  { id: "hospital_facility", label: "Hospital", description: "Hospital, inpatient care, acute care, or hospital department project.", sortOrder: 150 },
  { id: "dental", label: "Dental", description: "Dental, orthodontic, oral surgery, or dental specialty facility.", sortOrder: 160 },
  { id: "veterinary", label: "Veterinary", description: "Veterinary clinic, animal hospital, or animal care facility.", sortOrder: 170 },
  { id: "quick_service_restaurant", label: "Quick Service", description: "Quick service restaurant, fast casual, counter service, or takeout-focused restaurant.", sortOrder: 210 },
  { id: "full_service_restaurant", label: "Full Service", description: "Full service dining, table service restaurant, or similar food service space.", sortOrder: 220 },
  { id: "bar_lounge", label: "Bar / Lounge", description: "Bar, lounge, tavern, tasting room, or beverage-focused hospitality space.", sortOrder: 230 },
  { id: "cafe", label: "Cafe", description: "Cafe, coffee shop, bakery cafe, or light food service tenant space.", sortOrder: 240 },
  { id: "ghost_kitchen", label: "Ghost Kitchen", description: "Delivery-only kitchen, commissary kitchen, or multi-brand kitchen facility.", sortOrder: 250 },
  { id: "commercial_kitchen_only", label: "Commercial Kitchen Only", description: "Commercial kitchen scope without a public dining or sales area.", sortOrder: 260 },
  { id: "dry_warehouse", label: "Dry Warehouse", description: "Dry storage, general warehouse, or non-refrigerated storage facility.", sortOrder: 310 },
  { id: "cold_storage_facility", label: "Cold Storage", description: "Cold storage, refrigerated warehouse, freezer, or controlled temperature facility.", sortOrder: 320 },
  { id: "distribution_center", label: "Distribution Center", description: "Distribution, logistics, fulfillment, shipping, or receiving center.", sortOrder: 330 },
  { id: "flex_warehouse", label: "Flex Warehouse", description: "Flex warehouse with office, light industrial, showroom, or mixed warehouse uses.", sortOrder: 340 },
  { id: "manufacturing_warehouse", label: "Manufacturing Warehouse", description: "Manufacturing, production, assembly, or warehouse-production facility.", sortOrder: 350 },
  { id: "single_family", label: "Single Family", description: "Single-family residential project or custom home.", sortOrder: 410 },
  { id: "townhouse", label: "Townhouse", description: "Townhome, rowhouse, or attached residential unit project.", sortOrder: 420 },
  { id: "apartment_unit", label: "Apartment Unit", description: "Apartment unit, residential unit, or unit-level renovation.", sortOrder: 430 },
  { id: "common_area", label: "Common Area", description: "Residential or multifamily common area such as corridors, lobby, leasing, or shared support space.", sortOrder: 440 },
  { id: "clubhouse_amenity", label: "Clubhouse / Amenity", description: "Clubhouse, amenity, fitness, pool house, or residential amenity space.", sortOrder: 450 },
  { id: "mixed_use_residential", label: "Mixed-Use Residential", description: "Residential project mixed with retail, office, parking, amenity, or other uses.", sortOrder: 460 },
];

export const facilityTypeAvailabilityBySector: FacilityTypeAvailability[] = [
  { sector: "office", facilityTypes: ["general_office", "corporate_office", "professional_office", "bank_branch", "call_center", "coworking"] },
  { sector: "healthcare", facilityTypes: ["medical_office_facility", "clinic", "surgery_center_facility", "imaging_center", "hospital_facility", "dental", "veterinary"] },
  { sector: "restaurant", facilityTypes: ["quick_service_restaurant", "full_service_restaurant", "bar_lounge", "cafe", "ghost_kitchen", "commercial_kitchen_only"] },
  { sector: "warehouse", facilityTypes: ["dry_warehouse", "cold_storage_facility", "distribution_center", "flex_warehouse", "manufacturing_warehouse"] },
  { sector: "residential", facilityTypes: ["single_family", "townhouse", "mixed_use_residential"] },
  { sector: "multifamily", facilityTypes: ["apartment_unit", "common_area", "clubhouse_amenity", "mixed_use_residential"] },
];

export const projectProfileWorkTypeOptions: ProjectProfileOption<ProjectProfileWorkTypeId>[] = [
  {
    id: "interior_fit_out_renovation",
    label: "Interior Fit-Out / Renovation",
    description: "Interior work inside an existing building or shell. Includes TI, fit-out, build-out, interior renovation, remodel, and similar work.",
    sortOrder: 10,
  },
  { id: "ground_up_new_construction", label: "Ground-Up / New Construction", description: "New building construction from site/foundation through completed project.", sortOrder: 20 },
  { id: "core_and_shell", label: "Core & Shell", description: "Base building structure, enclosure, and primary systems without full tenant buildout.", sortOrder: 30 },
  { id: "addition_expansion", label: "Addition / Expansion", description: "New square footage added to an existing building or facility.", sortOrder: 40 },
  { id: "sitework_civil_only", label: "Sitework / Civil Only", description: "Site/civil scope without meaningful building interior scope.", sortOrder: 50 },
  { id: "demolition_abatement_only", label: "Demolition / Abatement Only", description: "Demolition, selective demolition, full demolition, or abatement package without rebuild scope.", sortOrder: 60 },
  { id: "restoration_adaptive_reuse", label: "Restoration / Adaptive Reuse", description: "Existing building restoration, preservation, reuse, conversion, or major rehabilitation.", sortOrder: 70 },
  { id: "maintenance_repair", label: "Maintenance / Repair", description: "Repair, replacement, maintenance, service, or small corrective construction scope.", sortOrder: 80 },
  { id: "specialty_systems_installation", label: "Specialty Systems Installation", description: "Narrow project focused primarily on a system, equipment package, or specialty scope.", sortOrder: 90 },
];

export const sectorWorkTypeLabels: SectorWorkTypeLabel[] = [
  { sector: "office", workType: "interior_fit_out_renovation", label: "Tenant Improvement / Interior Fit-Out" },
  { sector: "retail", workType: "interior_fit_out_renovation", label: "Store Build-Out / Renovation" },
  { sector: "restaurant", workType: "interior_fit_out_renovation", label: "Restaurant Build-Out / Renovation" },
  { sector: "healthcare", workType: "interior_fit_out_renovation", label: "Medical Office TI / Renovation" },
  { sector: "multifamily", workType: "interior_fit_out_renovation", label: "Unit Renovation / Remodel" },
  { sector: "residential", workType: "interior_fit_out_renovation", label: "Renovation / Remodel" },
  { sector: "hospitality", workType: "interior_fit_out_renovation", label: "Guestroom / Public Area Renovation" },
  { sector: "industrial", workType: "interior_fit_out_renovation", label: "Interior Renovation / Process Area Fit-Out" },
  { sector: "warehouse", workType: "interior_fit_out_renovation", label: "Warehouse Tenant Build-Out" },
  { sector: "laboratory", workType: "interior_fit_out_renovation", label: "Lab Renovation / Fit-Out" },
  { sector: "cleanroom", workType: "interior_fit_out_renovation", label: "Cleanroom Fit-Out / Renovation" },
];

export const projectProfileContextTagOptions: ProjectProfileOption<ProjectProfileContextTagId>[] = [
  { id: "occupied_site", label: "Occupied Site", description: "Work occurs in or adjacent to an occupied facility or active operation.", sortOrder: 10 },
  { id: "phased_work", label: "Phased Work", description: "Work requires planned phases, swing space, or sequencing constraints.", sortOrder: 20 },
  { id: "night_work", label: "Night Work", description: "Night, off-hours, weekend, or restricted-hour work is expected.", sortOrder: 30 },
  { id: "public_bid", label: "Public Bid", description: "Public solicitation, public owner, or public procurement requirements apply.", sortOrder: 40 },
  { id: "prevailing_wage", label: "Prevailing Wage", description: "Prevailing wage, Davis-Bacon, certified payroll, or wage-rate requirements apply.", sortOrder: 50 },
  { id: "secure_facility", label: "Secure Facility", description: "Secure access, background checks, badging, detention, or security constraints apply.", sortOrder: 60 },
  { id: "high_rise", label: "High-Rise", description: "High-rise, vertical logistics, elevator, pumping, hoisting, or fire/life safety complexity.", sortOrder: 70 },
  { id: "white_box", label: "White Box", description: "Basic interior preparation for future tenant or owner build-out.", sortOrder: 80 },
  { id: "furniture_ffe", label: "Furniture / FF&E", description: "Furniture, fixtures, equipment, systems furniture, artwork, or owner/vendor furnishings may affect scope.", sortOrder: 90 },
  { id: "access_control", label: "Access Control / Security", description: "Access control, security, badging, or monitored entry scope may affect trade visibility.", sortOrder: 100 },
  { id: "medical_office", label: "Medical Office", description: "Medical office, clinic, MOB, or outpatient care environment.", sortOrder: 110 },
  { id: "hospital", label: "Hospital", description: "Hospital, acute care, inpatient, or major healthcare facility.", sortOrder: 120 },
  { id: "surgery_center", label: "Surgery Center", description: "Ambulatory surgery, procedure, operating, or sterile clinical environment.", sortOrder: 130 },
  { id: "imaging", label: "Imaging", description: "Imaging, radiology, MRI, CT, X-ray, or shielding-sensitive scope.", sortOrder: 140 },
  { id: "infection_control", label: "Infection Control", description: "ICRA, infection control, containment, healthcare phasing, or sterile work controls.", sortOrder: 150 },
  { id: "medical_gas_required", label: "Medical Gas Required", description: "Medical gas infrastructure or tie-ins are expected.", sortOrder: 160 },
  { id: "nurse_call_required", label: "Nurse Call Required", description: "Nurse call, patient communications, or clinical low-voltage systems are expected.", sortOrder: 170 },
  { id: "radiation_shielding", label: "Radiation Shielding", description: "Radiation shielding, imaging shielding, or related protection scope is expected.", sortOrder: 180 },
  { id: "lead_lined_construction", label: "Lead-Lined Construction", description: "Lead-lined partitions, doors, frames, glazing, or shielding assemblies are expected.", sortOrder: 190 },
  { id: "commercial_kitchen", label: "Commercial Kitchen", description: "Commercial kitchen, food prep, hood, grease, refrigeration, or food service scope.", sortOrder: 200 },
  { id: "food_service", label: "Food Service", description: "Food service equipment or kitchen vendor coordination may be in scope.", sortOrder: 210 },
  { id: "kitchen_hood", label: "Kitchen Hood", description: "Kitchen hood, exhaust, fire suppression, and grease-related coordination may be in scope.", sortOrder: 220 },
  { id: "walk_in_cooler_freezer", label: "Walk-In Cooler / Freezer", description: "Walk-in cooler, freezer, refrigeration, or insulated food storage scope may be in scope.", sortOrder: 230 },
  { id: "grease_interceptor", label: "Grease Interceptor", description: "Grease interceptor or grease waste plumbing may be in scope.", sortOrder: 240 },
  { id: "refrigeration", label: "Refrigeration", description: "Refrigeration systems, piping, cases, or food/cold storage refrigeration may be in scope.", sortOrder: 250 },
  { id: "cold_storage", label: "Cold Storage", description: "Cold storage, freezer, cooler, insulated panel, or refrigeration-heavy facility.", sortOrder: 260 },
  { id: "food_processing", label: "Food Processing", description: "Food processing, washdown, sanitary, refrigeration, or production environment.", sortOrder: 270 },
  { id: "data_center", label: "Data Center", description: "Data center, server, mission-critical, redundant power/cooling, or uptime-driven work.", sortOrder: 280 },
  { id: "lab", label: "Lab", description: "Laboratory or technical research/testing scope.", sortOrder: 290 },
  { id: "cleanroom_context", label: "Cleanroom", description: "Cleanroom, controlled environment, or contamination-controlled area.", sortOrder: 300 },
  { id: "historic_restoration", label: "Historic Restoration", description: "Historic preservation, restoration, landmark, or sensitive existing fabric.", sortOrder: 310 },
  { id: "structural_retrofit", label: "Structural Retrofit", description: "Structural retrofit, strengthening, repair, or existing structure modifications are expected.", sortOrder: 320 },
  { id: "change_of_use", label: "Change of Use", description: "Existing building use changes and may affect code, systems, and scope assumptions.", sortOrder: 330 },
  { id: "tilt_up", label: "Tilt-Up", description: "Tilt-up concrete construction or related building system.", sortOrder: 340 },
  { id: "precast", label: "Precast", description: "Precast concrete structure, panels, plank, or components.", sortOrder: 350 },
  { id: "pre_engineered_metal_building", label: "Pre-Engineered Metal Building", description: "Pre-engineered metal building or PEMB system.", sortOrder: 360 },
  { id: "airport_secure_area", label: "Airport Secure Area", description: "Airport secure, airside, TSA, restricted access, or aviation security area.", sortOrder: 370 },
  { id: "marine_waterfront", label: "Marine / Waterfront", description: "Marine, waterfront, coastal, pier, dock, port, or flood/tidal-adjacent work.", sortOrder: 380 },
  { id: "flood_zone", label: "Flood Zone", description: "Flood zone, floodproofing, coastal, drainage, or elevated construction constraints.", sortOrder: 390 },
  { id: "sitework_scope", label: "Sitework Scope", description: "Sitework, civil, utility, paving, or landscape scope is materially part of the project.", sortOrder: 400 },
  { id: "exterior_envelope_scope", label: "Exterior Envelope Scope", description: "Exterior walls, waterproofing, facade, cladding, or envelope scope is materially part of the project.", sortOrder: 410 },
  { id: "roof_work", label: "Roof Work", description: "Roofing, reroofing, roof repair, or roof accessories are materially part of the project.", sortOrder: 420 },
  { id: "wood_framing", label: "Wood Framing", description: "Wood framing, stick framing, trusses, or similar residential framing scope is expected.", sortOrder: 430 },
  { id: "masonry_block_building", label: "Masonry / Block Building", description: "Masonry or block building systems materially affect scope.", sortOrder: 440 },
  { id: "kitchen_bath_renovation", label: "Kitchen / Bath Renovation", description: "Residential or multifamily kitchen and bath renovation scope is expected.", sortOrder: 450 },
  { id: "appliances", label: "Appliances", description: "Appliances, owner equipment, or residential appliance coordination may be in scope.", sortOrder: 460 },
  { id: "siding_exterior_cladding", label: "Siding / Exterior Cladding", description: "Siding, exterior cladding, or residential envelope scope is expected.", sortOrder: 470 },
  { id: "windows_exterior_doors", label: "Windows / Exterior Doors", description: "Windows, exterior doors, replacements, or exterior opening scope is expected.", sortOrder: 480 },
];

export const contextTagAvailability: ContextTagAvailability[] = [
  { contextTag: "occupied_site" },
  { contextTag: "phased_work" },
  { contextTag: "night_work" },
  { contextTag: "public_bid", sectors: ["government", "education", "civil_sitework", "transportation", "airport", "marine"] },
  { contextTag: "prevailing_wage", sectors: ["government", "education", "civil_sitework", "transportation", "airport", "marine"] },
  { contextTag: "secure_facility", sectors: ["office", "government", "detention", "healthcare", "transportation", "airport", "mission_critical"] },
  { contextTag: "high_rise", sectors: ["office", "hospitality", "multifamily", "residential", "commercial"] },
  { contextTag: "white_box", workTypes: ["interior_fit_out_renovation", "core_and_shell"] },
  { contextTag: "furniture_ffe", sectors: ["office", "hospitality", "education", "multifamily", "residential"] },
  { contextTag: "access_control", sectors: ["office", "retail", "healthcare", "education", "government", "detention", "warehouse", "mission_critical"] },
  { contextTag: "medical_office", sectors: ["healthcare"], facilityTypes: ["medical_office_facility", "clinic"] },
  { contextTag: "hospital", sectors: ["healthcare"], facilityTypes: ["hospital_facility"] },
  { contextTag: "surgery_center", sectors: ["healthcare"], facilityTypes: ["surgery_center_facility"] },
  { contextTag: "imaging", sectors: ["healthcare"], facilityTypes: ["imaging_center"] },
  { contextTag: "infection_control", sectors: ["healthcare"] },
  { contextTag: "medical_gas_required", sectors: ["healthcare", "laboratory"] },
  { contextTag: "nurse_call_required", sectors: ["healthcare"] },
  { contextTag: "radiation_shielding", sectors: ["healthcare", "laboratory"] },
  { contextTag: "lead_lined_construction", sectors: ["healthcare", "laboratory"] },
  { contextTag: "lab", sectors: ["laboratory", "healthcare", "education", "industrial"] },
  { contextTag: "cleanroom_context", sectors: ["cleanroom", "laboratory", "healthcare", "industrial"] },
  { contextTag: "commercial_kitchen", sectors: ["restaurant", "hospitality", "education", "healthcare", "commercial"], facilityTypes: ["quick_service_restaurant", "full_service_restaurant", "ghost_kitchen", "commercial_kitchen_only"] },
  { contextTag: "food_service", sectors: ["restaurant", "hospitality", "education", "healthcare"], facilityTypes: ["quick_service_restaurant", "full_service_restaurant", "bar_lounge", "cafe", "ghost_kitchen", "commercial_kitchen_only"] },
  { contextTag: "kitchen_hood", sectors: ["restaurant", "hospitality", "education", "healthcare"] },
  { contextTag: "walk_in_cooler_freezer", sectors: ["restaurant", "hospitality", "warehouse", "industrial", "agricultural"], facilityTypes: ["cold_storage_facility", "ghost_kitchen", "commercial_kitchen_only"] },
  { contextTag: "grease_interceptor", sectors: ["restaurant", "hospitality", "education", "healthcare"] },
  { contextTag: "refrigeration", sectors: ["restaurant", "hospitality", "warehouse", "industrial", "agricultural"] },
  { contextTag: "cold_storage", sectors: ["warehouse", "industrial", "restaurant", "agricultural"], facilityTypes: ["cold_storage_facility"] },
  { contextTag: "food_processing", sectors: ["industrial", "agricultural", "warehouse"] },
  { contextTag: "data_center", sectors: ["mission_critical", "office", "industrial", "warehouse"] },
  { contextTag: "historic_restoration", workTypes: ["restoration_adaptive_reuse"] },
  { contextTag: "structural_retrofit", workTypes: ["restoration_adaptive_reuse", "addition_expansion", "maintenance_repair"] },
  { contextTag: "change_of_use", workTypes: ["restoration_adaptive_reuse", "interior_fit_out_renovation"] },
  { contextTag: "tilt_up", sectors: ["warehouse", "industrial", "retail"], workTypes: ["ground_up_new_construction"] },
  { contextTag: "precast", sectors: ["warehouse", "industrial", "commercial", "multifamily"], workTypes: ["ground_up_new_construction", "core_and_shell"] },
  { contextTag: "pre_engineered_metal_building", sectors: ["warehouse", "industrial", "agricultural"], workTypes: ["ground_up_new_construction"] },
  { contextTag: "airport_secure_area", sectors: ["airport", "transportation"] },
  { contextTag: "marine_waterfront", sectors: ["marine"] },
  { contextTag: "flood_zone" },
  { contextTag: "sitework_scope", workTypes: ["ground_up_new_construction", "addition_expansion", "sitework_civil_only"] },
  { contextTag: "exterior_envelope_scope", workTypes: ["ground_up_new_construction", "core_and_shell", "addition_expansion", "restoration_adaptive_reuse", "maintenance_repair"] },
  { contextTag: "roof_work", workTypes: ["ground_up_new_construction", "core_and_shell", "addition_expansion", "restoration_adaptive_reuse", "maintenance_repair"] },
  { contextTag: "wood_framing", sectors: ["residential", "multifamily"], facilityTypes: ["single_family", "townhouse", "apartment_unit"] },
  { contextTag: "masonry_block_building", sectors: ["residential", "multifamily", "commercial"] },
  { contextTag: "kitchen_bath_renovation", sectors: ["residential", "multifamily"], facilityTypes: ["single_family", "townhouse", "apartment_unit"] },
  { contextTag: "appliances", sectors: ["residential", "multifamily", "hospitality"], facilityTypes: ["single_family", "townhouse", "apartment_unit"] },
  { contextTag: "siding_exterior_cladding", sectors: ["residential", "multifamily"], workTypes: ["interior_fit_out_renovation", "ground_up_new_construction", "maintenance_repair", "restoration_adaptive_reuse"] },
  { contextTag: "windows_exterior_doors", sectors: ["residential", "multifamily"], workTypes: ["interior_fit_out_renovation", "ground_up_new_construction", "maintenance_repair", "restoration_adaptive_reuse"] },
];

export const buildingConditionOptions: ProjectProfileOption<ProjectProfileBuildingCondition>[] = [
  { id: "new_construction", label: "New Construction", description: "New construction with no existing building to remain.", sortOrder: 10 },
  { id: "existing_to_remain", label: "Existing To Remain", description: "Existing building remains with limited alteration.", sortOrder: 20 },
  { id: "existing_to_renovate", label: "Existing To Renovate", description: "Existing building or space will be renovated.", sortOrder: 30 },
  { id: "partial_demolition", label: "Partial Demolition", description: "Project includes partial demolition before new or renovation work.", sortOrder: 40 },
  { id: "full_demolition", label: "Full Demolition", description: "Project includes full building demolition.", sortOrder: 50 },
  { id: "unknown", label: "Unknown", description: "Building condition is not yet known.", sortOrder: 90 },
];

export const structureTypeOptions: ProjectProfileOption<ProjectProfileStructureType>[] = [
  { id: "steel", label: "Steel", description: "Steel framed structure.", sortOrder: 10 },
  { id: "concrete", label: "Concrete", description: "Concrete framed structure.", sortOrder: 20 },
  { id: "masonry", label: "Masonry", description: "Masonry or block structure.", sortOrder: 30 },
  { id: "wood_framed", label: "Wood Framed", description: "Wood framed or stick-built structure.", sortOrder: 40 },
  { id: "pre_engineered_metal_building", label: "Pre-Engineered Metal Building", description: "PEMB or similar metal building system.", sortOrder: 50 },
  { id: "tilt_up", label: "Tilt-Up", description: "Tilt-up concrete structure.", sortOrder: 60 },
  { id: "precast", label: "Precast", description: "Precast concrete structure.", sortOrder: 70 },
  { id: "mixed", label: "Mixed", description: "Mixed or hybrid structural system.", sortOrder: 80 },
  { id: "unknown", label: "Unknown", description: "Structure type is not yet known.", sortOrder: 90 },
];

export const occupancyConditionOptions: ProjectProfileOption<ProjectProfileOccupancyCondition>[] = [
  { id: "vacant", label: "Vacant", description: "Project area is vacant during construction.", sortOrder: 10 },
  { id: "occupied", label: "Occupied", description: "Project area or adjacent area remains occupied.", sortOrder: 20 },
  { id: "partially_occupied", label: "Partially Occupied", description: "Project includes partially occupied spaces or phased turnover.", sortOrder: 30 },
  { id: "active_operations", label: "Active Operations", description: "Owner, tenant, or facility operations remain active during work.", sortOrder: 40 },
  { id: "unknown", label: "Unknown", description: "Occupancy condition is not yet known.", sortOrder: 90 },
];

export const scopeFlagOptions: ProjectProfileOption<ProjectProfileScopeFlag>[] = [
  { id: "included", label: "Included", description: "Scope is included or expected.", sortOrder: 10 },
  { id: "not_included", label: "Not Included", description: "Scope is not included or not expected.", sortOrder: 20 },
  { id: "tbd", label: "TBD", description: "Scope status needs review.", sortOrder: 30 },
];

export const siteWalkStatusOptions: ProjectProfileOption<ProjectSiteWalkStatus>[] = [
  { id: "scheduled", label: "Scheduled", description: "Site walk is scheduled.", sortOrder: 10 },
  { id: "tbd", label: "TBD", description: "Site walk status is not yet known.", sortOrder: 20 },
  { id: "not_applicable", label: "Not Applicable", description: "Site walk does not apply.", sortOrder: 30 },
];

export const logisticsConditionOptions: ProjectProfileOption<keyof Pick<
  import("./types").ProjectProfileLogistics,
  "occupiedSite" | "phasedWork" | "nightWork" | "restrictedAccess" | "secureFacility" | "highRise" | "limitedLaydown"
>>[] = [
  { id: "occupiedSite", label: "Occupied Site", description: "Existing operations or occupants remain active.", sortOrder: 10 },
  { id: "phasedWork", label: "Phased Work", description: "Work requires phasing or sequencing.", sortOrder: 20 },
  { id: "nightWork", label: "Night Work", description: "Work may occur at night or off-hours.", sortOrder: 30 },
  { id: "restrictedAccess", label: "Restricted Access", description: "Access constraints, badging, or restricted entry may apply.", sortOrder: 40 },
  { id: "secureFacility", label: "Secure Facility", description: "Security controls, background checks, or secure areas may apply.", sortOrder: 50 },
  { id: "highRise", label: "High-Rise", description: "Vertical logistics or high-rise conditions may affect work.", sortOrder: 60 },
  { id: "limitedLaydown", label: "Limited Laydown", description: "Laydown, staging, or storage space is constrained.", sortOrder: 70 },
];

export const publicPrivateStatusOptions: ProjectProfileOption<ProjectPublicPrivateStatus>[] = [
  { id: "public", label: "Public", description: "Public owner, public procurement, or public bid requirements apply.", sortOrder: 10 },
  { id: "private", label: "Private", description: "Private owner or private procurement.", sortOrder: 20 },
  { id: "public_private_partnership", label: "Public / Private Partnership", description: "Project includes public/private partnership requirements.", sortOrder: 30 },
  { id: "unknown", label: "Unknown", description: "Public/private status is not yet known.", sortOrder: 90 },
];

export const taxStatusOptions: ProjectProfileOption<ProjectTaxStatus>[] = [
  { id: "taxable", label: "Taxable", description: "Project is taxable.", sortOrder: 10 },
  { id: "tax_exempt", label: "Tax Exempt", description: "Project is tax exempt.", sortOrder: 20 },
  { id: "partially_tax_exempt", label: "Partially Tax Exempt", description: "Project has partial tax exemption requirements.", sortOrder: 30 },
  { id: "unknown", label: "Unknown", description: "Tax status is not yet known.", sortOrder: 90 },
];

export const contractTypeOptions: ProjectProfileOption<ProjectContractType>[] = [
  { id: "lump_sum", label: "Lump Sum", description: "Lump sum contract.", sortOrder: 10 },
  { id: "cost_plus", label: "Cost Plus", description: "Cost plus contract.", sortOrder: 20 },
  { id: "gmp", label: "GMP", description: "Guaranteed maximum price contract.", sortOrder: 30 },
  { id: "unit_price", label: "Unit Price", description: "Unit price contract.", sortOrder: 40 },
  { id: "design_build", label: "Design-Build", description: "Design-build contract.", sortOrder: 50 },
  { id: "cm_at_risk", label: "CM At Risk", description: "Construction manager at risk delivery.", sortOrder: 60 },
  { id: "unknown", label: "Unknown", description: "Contract type is not yet known.", sortOrder: 90 },
];

export const ownerVendorScopeOptions: ProjectProfileOption<ProjectOwnerVendorScope>[] = [
  { id: "none_known", label: "None Known", description: "No OFCI/OFOI/CFCI/NIC assumptions are known.", sortOrder: 10 },
  { id: "ofci", label: "OFCI", description: "Owner furnished, contractor installed.", sortOrder: 20 },
  { id: "ofoi", label: "OFOI", description: "Owner furnished, owner installed.", sortOrder: 30 },
  { id: "cfci", label: "CFCI", description: "Contractor furnished, contractor installed.", sortOrder: 40 },
  { id: "nic", label: "NIC", description: "Not in contract.", sortOrder: 50 },
  { id: "mixed", label: "Mixed", description: "Mixed owner/vendor scope assumptions.", sortOrder: 60 },
  { id: "unknown", label: "Unknown", description: "Owner/vendor scope is not yet known.", sortOrder: 90 },
];
