import {
  ContextTagAvailability,
  ProjectClassificationOption,
  ProjectContextTagId,
  ProjectSectorId,
  ProjectWorkTypeId,
  SectorWorkTypeLabel,
} from "./types";

export const projectSectorOptions: ProjectClassificationOption<ProjectSectorId>[] = [
  { id: "commercial", label: "Commercial", description: "General commercial project where no narrower sector has been selected.", sortOrder: 10 },
  { id: "office", label: "Office", description: "Office buildings, tenant suites, corporate interiors, and office fit-outs.", sortOrder: 20 },
  { id: "retail", label: "Retail", description: "Retail stores, shopping centers, storefronts, and sales environments.", sortOrder: 30 },
  { id: "restaurant", label: "Restaurant", description: "Restaurants, cafes, bars, commercial kitchens, and food service tenant spaces.", sortOrder: 40 },
  { id: "hospitality", label: "Hospitality", description: "Hotels, resorts, guestrooms, lobbies, amenity spaces, and hospitality back-of-house work.", sortOrder: 50 },
  { id: "healthcare", label: "Healthcare", description: "Medical office, clinic, hospital, surgery center, imaging, and healthcare support spaces.", sortOrder: 60 },
  { id: "education", label: "Education", description: "Schools, colleges, universities, classrooms, labs, cafeterias, and campus facilities.", sortOrder: 70 },
  { id: "industrial", label: "Industrial", description: "Industrial, manufacturing, process, utility, and production facilities.", sortOrder: 80 },
  { id: "warehouse", label: "Warehouse", description: "Warehouse, logistics, distribution, storage, fulfillment, and light industrial shell/buildout work.", sortOrder: 90 },
  { id: "laboratory", label: "Laboratory", description: "Laboratory, research, testing, and technical/scientific facilities.", sortOrder: 100 },
  { id: "cleanroom", label: "Cleanroom", description: "Cleanroom, controlled environment, and specialty technical production spaces.", sortOrder: 110 },
  { id: "multifamily", label: "Multifamily", description: "Apartment buildings, mixed-use residential, multifamily common areas, and unit renovations.", sortOrder: 120 },
  { id: "residential", label: "Residential", description: "Single-family residential, townhomes, custom homes, and residential remodels.", sortOrder: 130 },
  { id: "civil_sitework", label: "Civil / Sitework", description: "Site/civil, utilities, paving, earthwork, landscaping, and exterior development projects.", sortOrder: 140 },
  { id: "government", label: "Government", description: "Public agency, municipal, state, federal, and civic projects.", sortOrder: 150 },
  { id: "detention", label: "Detention", description: "Correctional, detention, holding, and secure custodial facilities.", sortOrder: 160 },
  { id: "transportation", label: "Transportation", description: "Transit, station, roadway, rail, airport, marine, and transportation infrastructure facilities.", sortOrder: 170 },
  { id: "airport", label: "Airport", description: "Airport, airfield, terminal, hangar, and secure aviation environments.", sortOrder: 180 },
  { id: "marine", label: "Marine / Waterfront", description: "Marine, dock, waterfront, pier, seawall, and shoreline work.", sortOrder: 190 },
  { id: "sports", label: "Sports / Recreation", description: "Athletic, recreation, sports fields, pools, performance, and event facilities.", sortOrder: 200 },
  { id: "mission_critical", label: "Mission Critical", description: "Data centers, critical facilities, UPS/generator-heavy environments, and resilient infrastructure.", sortOrder: 210 },
  { id: "renewable_energy", label: "Renewable Energy", description: "Solar, wind, EV charging, battery, and renewable infrastructure projects.", sortOrder: 220 },
  { id: "agricultural", label: "Agricultural", description: "Agricultural, greenhouse, grow, livestock, food production, and related facilities.", sortOrder: 230 },
];

export const projectWorkTypeOptions: ProjectClassificationOption<ProjectWorkTypeId>[] = [
  {
    id: "interior_fit_out_renovation",
    label: "Interior Fit-Out / Renovation",
    description: "Interior work inside an existing building or shell. Includes tenant improvement, fit-out, build-out, interior renovation, remodel, and similar work.",
    sortOrder: 10,
  },
  { id: "ground_up_new_construction", label: "Ground-Up / New Construction", description: "New building construction from site/foundation through completed project.", sortOrder: 20 },
  { id: "core_and_shell", label: "Core & Shell", description: "Base building structure, enclosure, and primary systems without full tenant buildout.", sortOrder: 30 },
  { id: "addition_expansion", label: "Addition / Expansion", description: "New square footage added to an existing building or facility.", sortOrder: 40 },
  { id: "sitework_civil_only", label: "Sitework / Civil Only", description: "Site/civil scope without meaningful building interior scope.", sortOrder: 50 },
  { id: "demolition_abatement_only", label: "Demolition / Abatement Only", description: "Demolition, selective demolition, full demolition, or abatement package without rebuild scope.", sortOrder: 60 },
  { id: "restoration_adaptive_reuse", label: "Restoration / Adaptive Reuse", description: "Existing building restoration, preservation, reuse, conversion, or major rehabilitation.", sortOrder: 70 },
  { id: "maintenance_repair", label: "Maintenance / Repair", description: "Repair, replacement, maintenance, service, or small corrective construction scope.", sortOrder: 80 },
  { id: "specialty_systems_installation", label: "Specialty Systems Installation", description: "Narrow project focused primarily on a system, equipment package, or specialty scope.", sortOrder: 90 },
];

export const sectorWorkTypeLabels: SectorWorkTypeLabel[] = [
  { sector: "office", workType: "interior_fit_out_renovation", label: "Tenant Improvement / Interior Fit-Out" },
  { sector: "retail", workType: "interior_fit_out_renovation", label: "Store Build-Out / Renovation" },
  { sector: "restaurant", workType: "interior_fit_out_renovation", label: "Restaurant Build-Out / Renovation" },
  { sector: "healthcare", workType: "interior_fit_out_renovation", label: "Medical Office TI / Renovation" },
  { sector: "multifamily", workType: "interior_fit_out_renovation", label: "Unit Renovation / Remodel" },
  { sector: "residential", workType: "interior_fit_out_renovation", label: "Renovation / Remodel" },
  { sector: "hospitality", workType: "interior_fit_out_renovation", label: "Guestroom / Public Area Renovation" },
  { sector: "industrial", workType: "interior_fit_out_renovation", label: "Interior Renovation / Process Area Fit-Out" },
  { sector: "warehouse", workType: "interior_fit_out_renovation", label: "Warehouse Tenant Build-Out" },
  { sector: "laboratory", workType: "interior_fit_out_renovation", label: "Lab Renovation / Fit-Out" },
  { sector: "cleanroom", workType: "interior_fit_out_renovation", label: "Cleanroom Fit-Out / Renovation" },
];

export const projectContextTagOptions: ProjectClassificationOption<ProjectContextTagId>[] = [
  { id: "occupied_site", label: "Occupied Site", description: "Work occurs in or adjacent to an occupied facility or active operation.", sortOrder: 10 },
  { id: "phased_work", label: "Phased Work", description: "Work requires planned phases, swing space, or sequencing constraints.", sortOrder: 20 },
  { id: "night_work", label: "Night Work", description: "Night, off-hours, weekend, or restricted-hour work is expected.", sortOrder: 30 },
  { id: "public_bid", label: "Public Bid", description: "Public solicitation, public owner, or public procurement requirements apply.", sortOrder: 40 },
  { id: "prevailing_wage", label: "Prevailing Wage", description: "Prevailing wage, Davis-Bacon, certified payroll, or wage-rate requirements apply.", sortOrder: 50 },
  { id: "secure_facility", label: "Secure Facility", description: "Secure access, background checks, badging, detention, or security constraints apply.", sortOrder: 60 },
  { id: "high_rise", label: "High-Rise", description: "High-rise, vertical logistics, elevator, pumping, hoisting, or fire/life safety complexity.", sortOrder: 70 },
  { id: "white_box", label: "White Box", description: "Basic interior preparation for future tenant or owner build-out.", sortOrder: 80 },
  { id: "furniture_ffe", label: "Furniture / FF&E", description: "Furniture, fixtures, equipment, systems furniture, artwork, or owner/vendor furnishings may affect scope.", sortOrder: 90 },
  { id: "access_control", label: "Access Control / Security", description: "Access control, security, badging, or monitored entry scope may affect trade visibility.", sortOrder: 100 },
  { id: "medical_office", label: "Medical Office", description: "Medical office, clinic, MOB, or outpatient care environment.", sortOrder: 110 },
  { id: "hospital", label: "Hospital", description: "Hospital, acute care, inpatient, or major healthcare facility.", sortOrder: 120 },
  { id: "surgery_center", label: "Surgery Center", description: "Ambulatory surgery, procedure, operating, or sterile clinical environment.", sortOrder: 130 },
  { id: "imaging", label: "Imaging", description: "Imaging, radiology, MRI, CT, X-ray, or shielding-sensitive scope.", sortOrder: 140 },
  { id: "infection_control", label: "Infection Control", description: "ICRA, infection control, containment, healthcare phasing, or sterile work controls.", sortOrder: 150 },
  { id: "medical_gas_required", label: "Medical Gas Required", description: "Medical gas infrastructure or tie-ins are expected.", sortOrder: 160 },
  { id: "nurse_call_required", label: "Nurse Call Required", description: "Nurse call, patient communications, or clinical low-voltage systems are expected.", sortOrder: 170 },
  { id: "radiation_shielding", label: "Radiation Shielding", description: "Radiation shielding, imaging shielding, or related protection scope is expected.", sortOrder: 180 },
  { id: "lead_lined_construction", label: "Lead-Lined Construction", description: "Lead-lined partitions, doors, frames, glazing, or shielding assemblies are expected.", sortOrder: 190 },
  { id: "commercial_kitchen", label: "Commercial Kitchen", description: "Commercial kitchen, food prep, hood, grease, refrigeration, or food service scope.", sortOrder: 200 },
  { id: "food_service", label: "Food Service", description: "Food service equipment or kitchen vendor coordination may be in scope.", sortOrder: 210 },
  { id: "kitchen_hood", label: "Kitchen Hood", description: "Kitchen hood, exhaust, fire suppression, and grease-related coordination may be in scope.", sortOrder: 220 },
  { id: "walk_in_cooler_freezer", label: "Walk-In Cooler / Freezer", description: "Walk-in cooler, freezer, refrigeration, or insulated food storage scope may be in scope.", sortOrder: 230 },
  { id: "grease_interceptor", label: "Grease Interceptor", description: "Grease interceptor or grease waste plumbing may be in scope.", sortOrder: 240 },
  { id: "refrigeration", label: "Refrigeration", description: "Refrigeration systems, piping, cases, or food/cold storage refrigeration may be in scope.", sortOrder: 250 },
  { id: "cold_storage", label: "Cold Storage", description: "Cold storage, freezer, cooler, insulated panel, or refrigeration-heavy facility.", sortOrder: 260 },
  { id: "food_processing", label: "Food Processing", description: "Food processing, washdown, sanitary, refrigeration, or production environment.", sortOrder: 270 },
  { id: "data_center", label: "Data Center", description: "Data center, server, mission-critical, redundant power/cooling, or uptime-driven work.", sortOrder: 280 },
  { id: "lab", label: "Lab", description: "Laboratory or technical research/testing scope.", sortOrder: 290 },
  { id: "cleanroom_context", label: "Cleanroom", description: "Cleanroom, controlled environment, or contamination-controlled area.", sortOrder: 300 },
  { id: "historic_restoration", label: "Historic Restoration", description: "Historic preservation, restoration, landmark, or sensitive existing fabric.", sortOrder: 310 },
  { id: "structural_retrofit", label: "Structural Retrofit", description: "Structural retrofit, strengthening, repair, or existing structure modifications are expected.", sortOrder: 320 },
  { id: "change_of_use", label: "Change of Use", description: "Existing building use changes and may affect code, systems, and scope assumptions.", sortOrder: 330 },
  { id: "tilt_up", label: "Tilt-Up", description: "Tilt-up concrete construction or related building system.", sortOrder: 340 },
  { id: "precast", label: "Precast", description: "Precast concrete structure, panels, plank, or components.", sortOrder: 350 },
  { id: "pre_engineered_metal_building", label: "Pre-Engineered Metal Building", description: "Pre-engineered metal building or PEMB system.", sortOrder: 360 },
  { id: "airport_secure_area", label: "Airport Secure Area", description: "Airport secure, airside, TSA, restricted access, or aviation security area.", sortOrder: 370 },
  { id: "marine_waterfront", label: "Marine / Waterfront", description: "Marine, waterfront, coastal, pier, dock, port, or flood/tidal-adjacent work.", sortOrder: 380 },
  { id: "flood_zone", label: "Flood Zone", description: "Flood zone, floodproofing, coastal, drainage, or elevated construction constraints.", sortOrder: 390 },
  { id: "sitework_scope", label: "Sitework Scope", description: "Sitework, civil, utility, paving, or landscape scope is materially part of the project.", sortOrder: 400 },
  { id: "exterior_envelope_scope", label: "Exterior Envelope Scope", description: "Exterior walls, waterproofing, facade, cladding, or envelope scope is materially part of the project.", sortOrder: 410 },
  { id: "roof_work", label: "Roof Work", description: "Roofing, reroofing, roof repair, or roof accessories are materially part of the project.", sortOrder: 420 },
  { id: "wood_framing", label: "Wood Framing", description: "Wood framing, stick framing, trusses, or similar residential framing scope is expected.", sortOrder: 430 },
  { id: "masonry_block_building", label: "Masonry / Block Building", description: "Masonry or block building systems materially affect scope.", sortOrder: 440 },
  { id: "kitchen_bath_renovation", label: "Kitchen / Bath Renovation", description: "Residential or multifamily kitchen and bath renovation scope is expected.", sortOrder: 450 },
  { id: "appliances", label: "Appliances", description: "Appliances, owner equipment, or residential appliance coordination may be in scope.", sortOrder: 460 },
  { id: "siding_exterior_cladding", label: "Siding / Exterior Cladding", description: "Siding, exterior cladding, or residential envelope scope is expected.", sortOrder: 470 },
  { id: "windows_exterior_doors", label: "Windows / Exterior Doors", description: "Windows, exterior doors, replacements, or exterior opening scope is expected.", sortOrder: 480 },
];

export const contextTagAvailability: ContextTagAvailability[] = [
  { contextTag: "occupied_site" },
  { contextTag: "phased_work" },
  { contextTag: "night_work" },
  { contextTag: "public_bid", sectors: ["government", "education", "civil_sitework", "transportation", "airport", "marine"] },
  { contextTag: "prevailing_wage", sectors: ["government", "education", "civil_sitework", "transportation", "airport", "marine"] },
  { contextTag: "secure_facility", sectors: ["office", "government", "detention", "healthcare", "transportation", "airport", "mission_critical"] },
  { contextTag: "high_rise", sectors: ["office", "hospitality", "multifamily", "residential", "commercial"] },
  { contextTag: "white_box", workTypes: ["interior_fit_out_renovation", "core_and_shell"] },
  { contextTag: "furniture_ffe", sectors: ["office", "hospitality", "education", "multifamily", "residential"] },
  { contextTag: "access_control", sectors: ["office", "retail", "healthcare", "education", "government", "detention", "warehouse", "mission_critical"] },
  { contextTag: "medical_office", sectors: ["healthcare"] },
  { contextTag: "hospital", sectors: ["healthcare"] },
  { contextTag: "surgery_center", sectors: ["healthcare"] },
  { contextTag: "imaging", sectors: ["healthcare"] },
  { contextTag: "infection_control", sectors: ["healthcare"] },
  { contextTag: "medical_gas_required", sectors: ["healthcare", "laboratory"] },
  { contextTag: "nurse_call_required", sectors: ["healthcare"] },
  { contextTag: "radiation_shielding", sectors: ["healthcare", "laboratory"] },
  { contextTag: "lead_lined_construction", sectors: ["healthcare", "laboratory"] },
  { contextTag: "lab", sectors: ["laboratory", "healthcare", "education", "industrial"] },
  { contextTag: "cleanroom_context", sectors: ["cleanroom", "laboratory", "healthcare", "industrial"] },
  { contextTag: "commercial_kitchen", sectors: ["restaurant", "hospitality", "education", "healthcare", "commercial"] },
  { contextTag: "food_service", sectors: ["restaurant", "hospitality", "education", "healthcare"] },
  { contextTag: "kitchen_hood", sectors: ["restaurant", "hospitality", "education", "healthcare"] },
  { contextTag: "walk_in_cooler_freezer", sectors: ["restaurant", "hospitality", "warehouse", "industrial", "agricultural"] },
  { contextTag: "grease_interceptor", sectors: ["restaurant", "hospitality", "education", "healthcare"] },
  { contextTag: "refrigeration", sectors: ["restaurant", "hospitality", "warehouse", "industrial", "agricultural"] },
  { contextTag: "cold_storage", sectors: ["warehouse", "industrial", "restaurant", "agricultural"] },
  { contextTag: "food_processing", sectors: ["industrial", "agricultural", "warehouse"] },
  { contextTag: "data_center", sectors: ["mission_critical", "office", "industrial", "warehouse"] },
  { contextTag: "historic_restoration", workTypes: ["restoration_adaptive_reuse"] },
  { contextTag: "structural_retrofit", workTypes: ["restoration_adaptive_reuse", "addition_expansion", "maintenance_repair"] },
  { contextTag: "change_of_use", workTypes: ["restoration_adaptive_reuse", "interior_fit_out_renovation"] },
  { contextTag: "tilt_up", sectors: ["warehouse", "industrial", "retail"], workTypes: ["ground_up_new_construction"] },
  { contextTag: "precast", sectors: ["warehouse", "industrial", "commercial", "multifamily"], workTypes: ["ground_up_new_construction", "core_and_shell"] },
  { contextTag: "pre_engineered_metal_building", sectors: ["warehouse", "industrial", "agricultural"], workTypes: ["ground_up_new_construction"] },
  { contextTag: "airport_secure_area", sectors: ["airport", "transportation"] },
  { contextTag: "marine_waterfront", sectors: ["marine"] },
  { contextTag: "flood_zone" },
  { contextTag: "sitework_scope", workTypes: ["ground_up_new_construction", "addition_expansion", "sitework_civil_only"] },
  { contextTag: "exterior_envelope_scope", workTypes: ["ground_up_new_construction", "core_and_shell", "addition_expansion", "restoration_adaptive_reuse", "maintenance_repair"] },
  { contextTag: "roof_work", workTypes: ["ground_up_new_construction", "core_and_shell", "addition_expansion", "restoration_adaptive_reuse", "maintenance_repair"] },
  { contextTag: "wood_framing", sectors: ["residential", "multifamily"] },
  { contextTag: "masonry_block_building", sectors: ["residential", "multifamily", "commercial"] },
  { contextTag: "kitchen_bath_renovation", sectors: ["residential", "multifamily"] },
  { contextTag: "appliances", sectors: ["residential", "multifamily", "hospitality"] },
  { contextTag: "siding_exterior_cladding", sectors: ["residential", "multifamily"], workTypes: ["interior_fit_out_renovation", "ground_up_new_construction", "maintenance_repair", "restoration_adaptive_reuse"] },
  { contextTag: "windows_exterior_doors", sectors: ["residential", "multifamily"], workTypes: ["interior_fit_out_renovation", "ground_up_new_construction", "maintenance_repair", "restoration_adaptive_reuse"] },
];
