import {
  ProjectClassificationOption,
  ProjectContextTagId,
  ProjectSectorId,
  ProjectWorkTypeId,
} from "./types";

export const projectSectorOptions: ProjectClassificationOption<ProjectSectorId>[] = [
  {
    id: "commercial",
    label: "Commercial",
    description: "General commercial building work that does not fit a more specific sector.",
    sortOrder: 10,
  },
  {
    id: "office",
    label: "Office",
    description: "Office buildings, office suites, and workplace improvements.",
    sortOrder: 20,
    aliases: ["corporate office", "workplace"],
  },
  {
    id: "retail",
    label: "Retail",
    description: "Retail stores, shopping centers, showrooms, and customer-facing sales space.",
    sortOrder: 30,
  },
  {
    id: "restaurant",
    label: "Restaurant",
    description: "Restaurants, bars, cafes, commercial kitchens, and dining venues.",
    sortOrder: 40,
    aliases: ["food and beverage", "food service"],
  },
  {
    id: "hospitality",
    label: "Hospitality",
    description: "Hotels, resorts, event venues, and guest-facing hospitality work.",
    sortOrder: 50,
  },
  {
    id: "healthcare",
    label: "Healthcare",
    description: "Healthcare facilities, clinics, hospitals, surgery centers, and medical suites.",
    sortOrder: 60,
    aliases: ["medical"],
  },
  {
    id: "education",
    label: "Education",
    description: "K-12, higher education, training, and campus facilities.",
    sortOrder: 70,
  },
  {
    id: "industrial",
    label: "Industrial",
    description: "Manufacturing, production, process, and heavy-use industrial facilities.",
    sortOrder: 80,
  },
  {
    id: "warehouse",
    label: "Warehouse",
    description: "Warehouse, distribution, logistics, and storage facilities.",
    sortOrder: 90,
  },
  {
    id: "laboratory",
    label: "Laboratory",
    description: "Research, testing, laboratory, and technical science facilities.",
    sortOrder: 100,
    aliases: ["lab"],
  },
  {
    id: "cleanroom",
    label: "Cleanroom",
    description: "Controlled environment, clean manufacturing, and cleanroom facilities.",
    sortOrder: 110,
  },
  {
    id: "multifamily",
    label: "Multifamily",
    description: "Apartments, condominiums, student housing, and multi-unit residential work.",
    sortOrder: 120,
  },
  {
    id: "residential",
    label: "Residential",
    description: "Single-family, townhome, and residential improvement work.",
    sortOrder: 130,
  },
  {
    id: "civil",
    label: "Civil",
    description: "Civil infrastructure, roads, utilities, and site/civil work.",
    sortOrder: 140,
  },
  {
    id: "sitework",
    label: "Sitework",
    description: "Site-focused scopes such as earthwork, utilities, paving, and landscaping.",
    sortOrder: 150,
  },
  {
    id: "government",
    label: "Government",
    description: "Public agency, municipal, state, federal, and civic projects.",
    sortOrder: 160,
  },
  {
    id: "detention",
    label: "Detention",
    description: "Correctional, detention, secure custody, and justice facilities.",
    sortOrder: 170,
  },
  {
    id: "transportation",
    label: "Transportation",
    description: "Transit, rail, roadway, station, and transportation-related facilities.",
    sortOrder: 180,
  },
  {
    id: "airport",
    label: "Airport",
    description: "Airport, terminal, hangar, airfield, and aviation facilities.",
    sortOrder: 190,
  },
  {
    id: "marine",
    label: "Marine",
    description: "Marine, waterfront, port, pier, and coastal facilities.",
    sortOrder: 200,
  },
  {
    id: "sports",
    label: "Sports",
    description: "Athletic, recreation, stadium, arena, and sports facility projects.",
    sortOrder: 210,
  },
  {
    id: "mission_critical",
    label: "Mission Critical",
    description: "Data centers, critical operations, high-resilience, and uptime-sensitive work.",
    sortOrder: 220,
    aliases: ["mission-critical"],
  },
  {
    id: "renewable_energy",
    label: "Renewable Energy",
    description: "Solar, wind, energy storage, EV, and renewable-energy projects.",
    sortOrder: 230,
  },
  {
    id: "agricultural",
    label: "Agricultural",
    description: "Agricultural, greenhouse, food production, and farm-related facilities.",
    sortOrder: 240,
  },
];

export const projectWorkTypeOptions: ProjectClassificationOption<ProjectWorkTypeId>[] = [
  {
    id: "tenant_improvement",
    label: "Tenant Improvement",
    description: "Interior tenant scope within an existing building or shell.",
    sortOrder: 10,
    aliases: ["TI", "tenant build-out"],
  },
  {
    id: "fit_out",
    label: "Fit-Out",
    description: "Interior fit-out of space for occupancy or a specific use.",
    sortOrder: 20,
    aliases: ["fit out"],
  },
  {
    id: "build_out",
    label: "Build-Out",
    description: "Build-out of a shell, suite, tenant area, or defined project space.",
    sortOrder: 30,
    aliases: ["build out"],
  },
  {
    id: "interior_renovation",
    label: "Interior Renovation",
    description: "Interior renovation work within an existing building.",
    sortOrder: 40,
  },
  {
    id: "occupied_renovation",
    label: "Occupied Renovation",
    description: "Renovation performed while the facility remains partially or fully occupied.",
    sortOrder: 50,
  },
  {
    id: "ground_up",
    label: "Ground-Up",
    description: "New building construction from site/foundations through completion.",
    sortOrder: 60,
    aliases: ["new construction"],
  },
  {
    id: "core_and_shell",
    label: "Core & Shell",
    description: "Base building core, shell, structure, envelope, and primary systems.",
    sortOrder: 70,
    aliases: ["core and shell"],
  },
  {
    id: "shell_completion",
    label: "Shell Completion",
    description: "Completion or improvement of an existing shell condition.",
    sortOrder: 80,
  },
  {
    id: "white_box",
    label: "White Box",
    description: "Basic interior preparation for future tenant or owner build-out.",
    sortOrder: 90,
    aliases: ["warm shell", "vanilla shell"],
  },
  {
    id: "addition",
    label: "Addition",
    description: "Building addition or expansion connected to existing facilities.",
    sortOrder: 100,
  },
  {
    id: "remodel",
    label: "Remodel",
    description: "Remodel of an existing building, area, or suite.",
    sortOrder: 110,
  },
  {
    id: "adaptive_reuse",
    label: "Adaptive Reuse",
    description: "Conversion of an existing building to a new use.",
    sortOrder: 120,
  },
  {
    id: "restoration",
    label: "Restoration",
    description: "Restoration, preservation, or repair of existing/historic conditions.",
    sortOrder: 130,
  },
  {
    id: "sitework_only",
    label: "Sitework Only",
    description: "Project scope is limited primarily to site/civil work.",
    sortOrder: 140,
  },
  {
    id: "demolition_only",
    label: "Demolition Only",
    description: "Project scope is limited primarily to demolition or abatement work.",
    sortOrder: 150,
  },
  {
    id: "maintenance_repair",
    label: "Maintenance / Repair",
    description: "Maintenance, repair, replacement, or limited corrective work.",
    sortOrder: 160,
  },
  {
    id: "phased_renovation",
    label: "Phased Renovation",
    description: "Renovation requiring planned phases, swing space, or sequencing constraints.",
    sortOrder: 170,
  },
];

export const projectContextTagOptions: ProjectClassificationOption<ProjectContextTagId>[] = [
  {
    id: "medical_office",
    label: "Medical Office",
    description: "Medical office, clinic, MOB, or outpatient care environment.",
    sortOrder: 10,
    aliases: ["MOB", "clinic"],
  },
  {
    id: "hospital",
    label: "Hospital",
    description: "Hospital, acute care, inpatient, or major healthcare facility.",
    sortOrder: 20,
  },
  {
    id: "surgery_center",
    label: "Surgery Center",
    description: "Ambulatory surgery, procedure, operating, or sterile clinical environment.",
    sortOrder: 30,
    aliases: ["ASC", "operating room"],
  },
  {
    id: "imaging",
    label: "Imaging",
    description: "Imaging, radiology, MRI, CT, X-ray, or shielding-sensitive scope.",
    sortOrder: 40,
  },
  {
    id: "lab",
    label: "Lab",
    description: "Laboratory or technical research/testing scope.",
    sortOrder: 50,
    aliases: ["laboratory"],
  },
  {
    id: "cleanroom",
    label: "Cleanroom",
    description: "Cleanroom, controlled environment, or contamination-controlled area.",
    sortOrder: 60,
  },
  {
    id: "commercial_kitchen",
    label: "Commercial Kitchen",
    description: "Commercial kitchen, food prep, hood, grease, refrigeration, or food service scope.",
    sortOrder: 70,
  },
  {
    id: "occupied_building",
    label: "Occupied Building",
    description: "Work occurs in or adjacent to an occupied facility.",
    sortOrder: 80,
  },
  {
    id: "night_work",
    label: "Night Work",
    description: "Night, off-hours, weekend, or restricted-hour work is expected.",
    sortOrder: 90,
  },
  {
    id: "public_bid",
    label: "Public Bid",
    description: "Public solicitation, public owner, or public procurement requirements apply.",
    sortOrder: 100,
  },
  {
    id: "prevailing_wage",
    label: "Prevailing Wage",
    description: "Prevailing wage, Davis-Bacon, certified payroll, or wage-rate requirements apply.",
    sortOrder: 110,
  },
  {
    id: "secure_facility",
    label: "Secure Facility",
    description: "Secure access, background checks, badging, detention, or security constraints apply.",
    sortOrder: 120,
  },
  {
    id: "high_rise",
    label: "High-Rise",
    description: "High-rise, vertical logistics, elevator, pumping, hoisting, or fire/life safety complexity.",
    sortOrder: 130,
  },
  {
    id: "tilt_up",
    label: "Tilt-Up",
    description: "Tilt-up concrete construction or related building system.",
    sortOrder: 140,
  },
  {
    id: "precast",
    label: "Precast",
    description: "Precast concrete structure, panels, plank, or components.",
    sortOrder: 150,
  },
  {
    id: "pre_engineered_metal_building",
    label: "Pre-Engineered Metal Building",
    description: "Pre-engineered metal building or PEMB system.",
    sortOrder: 160,
    aliases: ["PEMB", "metal building"],
  },
  {
    id: "cold_storage",
    label: "Cold Storage",
    description: "Cold storage, freezer, cooler, insulated panel, or refrigeration-heavy facility.",
    sortOrder: 170,
  },
  {
    id: "food_processing",
    label: "Food Processing",
    description: "Food processing, washdown, sanitary, refrigeration, or production environment.",
    sortOrder: 180,
  },
  {
    id: "data_center",
    label: "Data Center",
    description: "Data center, server, mission-critical, redundant power/cooling, or uptime-driven work.",
    sortOrder: 190,
  },
  {
    id: "airport_secure_area",
    label: "Airport Secure Area",
    description: "Airport secure, airside, TSA, restricted access, or aviation security area.",
    sortOrder: 200,
  },
  {
    id: "marine_waterfront",
    label: "Marine / Waterfront",
    description: "Marine, waterfront, coastal, pier, dock, port, or flood/tidal-adjacent work.",
    sortOrder: 210,
  },
  {
    id: "historic_restoration",
    label: "Historic Restoration",
    description: "Historic preservation, restoration, landmark, or sensitive existing fabric.",
    sortOrder: 220,
  },
  {
    id: "flood_zone",
    label: "Flood Zone",
    description: "Flood zone, floodproofing, coastal, drainage, or elevated construction constraints.",
    sortOrder: 230,
  },
  {
    id: "infection_control",
    label: "Infection Control",
    description: "ICRA, infection control, containment, healthcare phasing, or sterile work controls.",
    sortOrder: 240,
    aliases: ["ICRA"],
  },
];
