import type { CsiToTradeMappingRule } from "./types";

export const CSI_MAPPING_PRIORITY_2004_PLUS_PROJECT = [
  "project override",
  "company override",
  "direct 2004+ rule",
  "2004+ code pattern",
  "2004+ keyword",
  "crosswalk to 1995 fallback",
  "generic fallback",
  "unassigned",
] as const;

export const CSI_MAPPING_PRIORITY_1995_PROJECT = [
  "project override",
  "company override",
  "direct 1995 rule",
  "1995 code pattern",
  "1995 keyword",
  "crosswalk to 2004+ fallback",
  "generic fallback",
  "unassigned",
] as const;

export const VERSION_AWARE_CSI_MAPPING_REQUIREMENTS = {
  preserveOriginalCoverage: true,
  deriveAlternateCoverage: true,
  directProjectVersionMatchFirst: true,
  useCrosswalkFallback: true,
  preserveMappingExplanation: true,
  groupEstimateReviewByProjectCsiVersion: true,
  groupBidLevelingByProjectCsiVersion: true,
} as const;

export const defaultCsiTradeMappingRules: CsiToTradeMappingRule[] = [
  {
    id: "2004-plus-gypsum-board",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["09 29"],
    titleKeywords: ["gypsum board", "drywall"],
    tradeId: "drywall-framing",
    specializationId: "gypsum-board",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "1995-gypsum-board",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["09250", "0925"],
    titleKeywords: ["gypsum board", "drywall"],
    tradeId: "drywall-framing",
    specializationId: "gypsum-board",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "2004-plus-non-structural-metal-framing",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["09 22"],
    titleKeywords: ["non-structural metal framing", "metal stud", "metal support assemblies"],
    tradeId: "drywall-framing",
    specializationId: "non-structural-metal-framing",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "1995-metal-support-assemblies",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["09110", "0911"],
    titleKeywords: ["metal support assemblies", "metal stud", "metal framing"],
    tradeId: "drywall-framing",
    specializationId: "non-structural-metal-framing",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "2004-plus-acoustical-ceilings",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["09 51"],
    titleKeywords: ["acoustical ceilings", "acoustic ceilings", "act"],
    tradeId: "ceilings",
    specializationId: "acoustical-ceilings",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "1995-acoustical-ceilings",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["09510", "0951"],
    titleKeywords: ["acoustical ceilings", "acoustic ceilings", "act"],
    tradeId: "ceilings",
    specializationId: "acoustical-ceilings",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "2004-plus-carpet",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["09 68"],
    titleKeywords: ["carpet", "carpeting", "carpet tile"],
    tradeId: "flooring",
    specializationId: "carpet",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "1995-carpet",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["09680", "0968"],
    titleKeywords: ["carpet", "carpeting", "carpet tile"],
    tradeId: "flooring",
    specializationId: "carpet",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "2004-plus-resilient-flooring",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["09 65"],
    titleKeywords: ["resilient flooring", "lvt", "vinyl flooring", "sheet vinyl"],
    tradeId: "flooring",
    specializationId: "resilient-flooring-lvt",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "1995-resilient-flooring",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["09650", "0965"],
    titleKeywords: ["resilient flooring", "lvt", "vinyl flooring", "sheet vinyl"],
    tradeId: "flooring",
    specializationId: "resilient-flooring-lvt",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "2004-plus-tile",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["09 30"],
    titleKeywords: ["tiling", "tile"],
    tradeId: "flooring",
    specializationId: "tile",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "1995-tile",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["09300", "0930"],
    titleKeywords: ["tiling", "tile"],
    tradeId: "flooring",
    specializationId: "tile",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "2004-plus-painting-coatings",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["09 90"],
    titleKeywords: ["painting", "coatings", "paint"],
    tradeId: "painting-coatings",
    specializationId: "painting-coatings-specialization",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "1995-painting-coatings",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["09900", "0990"],
    titleKeywords: ["painting", "coatings", "paint"],
    tradeId: "painting-coatings",
    specializationId: "painting-coatings-specialization",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "2004-plus-plumbing",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["22"],
    titleKeywords: ["plumbing", "domestic water", "sanitary", "fixtures"],
    tradeId: "plumbing",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "1995-plumbing",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["15"],
    titleKeywords: ["plumbing", "domestic water", "sanitary", "fixtures"],
    tradeId: "plumbing",
    matchStrength: "PRIMARY",
    confidence: "MEDIUM",
    notes: "1995 Division 15 also includes mechanical/HVAC scope; estimator review may be needed.",
  },
  {
    id: "2004-plus-hvac",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["23"],
    titleKeywords: ["hvac", "mechanical", "duct", "air distribution"],
    tradeId: "hvac",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "1995-hvac",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["15"],
    titleKeywords: ["hvac", "mechanical", "duct", "air distribution"],
    tradeId: "hvac",
    matchStrength: "PRIMARY",
    confidence: "MEDIUM",
    notes: "1995 Division 15 also includes plumbing scope; estimator review may be needed.",
  },
  {
    id: "2004-plus-electrical",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["26"],
    titleKeywords: ["electrical", "lighting", "power", "panels"],
    tradeId: "electrical",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "1995-electrical",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["16"],
    titleKeywords: ["electrical", "lighting", "power", "panels"],
    tradeId: "electrical",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "2004-plus-low-voltage",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["27", "28"],
    titleKeywords: ["communications", "low voltage", "security", "access control", "data"],
    tradeId: "low-voltage-technology",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
  },
  {
    id: "1995-low-voltage",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["16700", "1670"],
    titleKeywords: ["communications", "low voltage", "security", "access control", "data"],
    tradeId: "low-voltage-technology",
    matchStrength: "PRIMARY",
    confidence: "MEDIUM",
  },
  {
    id: "2004-plus-fire-alarm",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["28 31"],
    titleKeywords: ["fire alarm"],
    tradeId: "low-voltage-technology",
    specializationId: "fire-alarm",
    matchStrength: "SECONDARY",
    confidence: "MEDIUM",
    possibleTradeIds: ["electrical", "fire-protection"],
    notes: "Fire alarm may be carried by low voltage, electrical, or fire protection depending company practice.",
  },
  {
    id: "1995-fire-alarm",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["16720", "1672"],
    titleKeywords: ["fire alarm"],
    tradeId: "low-voltage-technology",
    specializationId: "fire-alarm",
    matchStrength: "SECONDARY",
    confidence: "MEDIUM",
    possibleTradeIds: ["electrical", "fire-protection"],
    notes: "Fire alarm may be carried by low voltage, electrical, or fire protection depending company practice.",
  },
  {
    id: "2004-plus-medical-gas",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["22 62"],
    titleKeywords: ["medical gas", "med gas"],
    tradeId: "plumbing",
    specializationId: "medical-gas",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
    sectorTags: ["healthcare"],
    contextTags: ["medical_office", "hospital", "surgery_center"],
  },
  {
    id: "1995-medical-gas",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["15210", "1521"],
    titleKeywords: ["medical gas", "med gas"],
    tradeId: "plumbing",
    specializationId: "medical-gas",
    matchStrength: "PRIMARY",
    confidence: "MEDIUM",
    sectorTags: ["healthcare"],
    contextTags: ["medical_office", "hospital", "surgery_center"],
  },
  {
    id: "2004-plus-food-service-equipment",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["11 40"],
    titleKeywords: ["food service", "kitchen equipment", "commercial kitchen"],
    tradeId: "food-service-systems",
    specializationId: "food-service-equipment",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
    sectorTags: ["restaurant"],
    contextTags: ["commercial_kitchen"],
  },
  {
    id: "1995-food-service-equipment",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["11400", "1140"],
    titleKeywords: ["food service", "kitchen equipment", "commercial kitchen"],
    tradeId: "food-service-systems",
    specializationId: "food-service-equipment",
    matchStrength: "PRIMARY",
    confidence: "HIGH",
    sectorTags: ["restaurant"],
    contextTags: ["commercial_kitchen"],
  },
  {
    id: "2004-plus-insulation-ambiguous",
    csiVersion: "MASTERFORMAT_2004_PLUS",
    csiCodePatterns: ["07 21", "09 81"],
    titleKeywords: ["insulation", "acoustic insulation", "thermal insulation"],
    tradeId: "insulation",
    matchStrength: "POSSIBLE",
    confidence: "LOW",
    possibleTradeIds: ["drywall-framing", "ceilings", "roofing"],
    notes: "Insulation may belong to drywall, envelope, roofing, or specialty acoustic scope.",
  },
  {
    id: "1995-insulation-ambiguous",
    csiVersion: "MASTERFORMAT_1995",
    csiCodePatterns: ["07210", "0721", "09840", "0984"],
    titleKeywords: ["insulation", "acoustic insulation", "thermal insulation"],
    tradeId: "insulation",
    matchStrength: "POSSIBLE",
    confidence: "LOW",
    possibleTradeIds: ["drywall-framing", "ceilings", "roofing"],
    notes: "Insulation may belong to drywall, envelope, roofing, or specialty acoustic scope.",
  },
];
